// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.4
// source: fiat-provider.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Currency } from "./currency";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "tgvalidatord";

export interface FiatProviderAccount {
  id: string;
  provider: string;
  label: string;
  accountType: string;
  accountIdentifier: string;
  accountName: string;
  totalBalance: string;
  creationDate: Date | undefined;
  updateDate: Date | undefined;
  currencyID: string;
  currencyInfo: Currency | undefined;
  baseCurrencyValuation: string;
}

export interface FiatProviderCounterpartyAccount {
  id: string;
  provider: string;
  label: string;
  accountType: string;
  accountIdentifier: string;
  accountName: string;
  counterpartyID: string;
  counterpartyName: string;
  creationDate: Date | undefined;
  updateDate: Date | undefined;
  currencyID: string;
  currencyInfo: Currency | undefined;
}

export interface FiatProvider {
  provider: string;
  label: string;
  baseCurrencyValuation: string;
}

export interface FiatProviderOperation {
  id: string;
  provider: string;
  label: string;
  operationType: string;
  operationIdentifier: string;
  amount: string;
  creationDate: Date | undefined;
  updateDate: Date | undefined;
  currencyID: string;
  currencyInfo: Currency | undefined;
  operationDirection: string;
  fromAccountID: string;
  toAccountID: string;
  fromDetails: string;
  toDetails: string;
  status: string;
  comment: string;
  operationDetails: string;
}

function createBaseFiatProviderAccount(): FiatProviderAccount {
  return {
    id: "",
    provider: "",
    label: "",
    accountType: "",
    accountIdentifier: "",
    accountName: "",
    totalBalance: "",
    creationDate: undefined,
    updateDate: undefined,
    currencyID: "",
    currencyInfo: undefined,
    baseCurrencyValuation: "",
  };
}

export const FiatProviderAccount = {
  encode(message: FiatProviderAccount, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.provider !== "") {
      writer.uint32(18).string(message.provider);
    }
    if (message.label !== "") {
      writer.uint32(26).string(message.label);
    }
    if (message.accountType !== "") {
      writer.uint32(34).string(message.accountType);
    }
    if (message.accountIdentifier !== "") {
      writer.uint32(42).string(message.accountIdentifier);
    }
    if (message.accountName !== "") {
      writer.uint32(50).string(message.accountName);
    }
    if (message.totalBalance !== "") {
      writer.uint32(58).string(message.totalBalance);
    }
    if (message.creationDate !== undefined) {
      Timestamp.encode(toTimestamp(message.creationDate), writer.uint32(66).fork()).ldelim();
    }
    if (message.updateDate !== undefined) {
      Timestamp.encode(toTimestamp(message.updateDate), writer.uint32(74).fork()).ldelim();
    }
    if (message.currencyID !== "") {
      writer.uint32(82).string(message.currencyID);
    }
    if (message.currencyInfo !== undefined) {
      Currency.encode(message.currencyInfo, writer.uint32(90).fork()).ldelim();
    }
    if (message.baseCurrencyValuation !== "") {
      writer.uint32(98).string(message.baseCurrencyValuation);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): FiatProviderAccount {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFiatProviderAccount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.provider = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.label = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.accountType = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.accountIdentifier = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.accountName = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.totalBalance = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.creationDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.updateDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.currencyID = reader.string();
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.currencyInfo = Currency.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.baseCurrencyValuation = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FiatProviderAccount {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      provider: isSet(object.provider) ? globalThis.String(object.provider) : "",
      label: isSet(object.label) ? globalThis.String(object.label) : "",
      accountType: isSet(object.accountType) ? globalThis.String(object.accountType) : "",
      accountIdentifier: isSet(object.accountIdentifier) ? globalThis.String(object.accountIdentifier) : "",
      accountName: isSet(object.accountName) ? globalThis.String(object.accountName) : "",
      totalBalance: isSet(object.totalBalance) ? globalThis.String(object.totalBalance) : "",
      creationDate: isSet(object.creationDate) ? fromJsonTimestamp(object.creationDate) : undefined,
      updateDate: isSet(object.updateDate) ? fromJsonTimestamp(object.updateDate) : undefined,
      currencyID: isSet(object.currencyID) ? globalThis.String(object.currencyID) : "",
      currencyInfo: isSet(object.currencyInfo) ? Currency.fromJSON(object.currencyInfo) : undefined,
      baseCurrencyValuation: isSet(object.baseCurrencyValuation) ? globalThis.String(object.baseCurrencyValuation) : "",
    };
  },

  toJSON(message: FiatProviderAccount): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.provider !== "") {
      obj.provider = message.provider;
    }
    if (message.label !== "") {
      obj.label = message.label;
    }
    if (message.accountType !== "") {
      obj.accountType = message.accountType;
    }
    if (message.accountIdentifier !== "") {
      obj.accountIdentifier = message.accountIdentifier;
    }
    if (message.accountName !== "") {
      obj.accountName = message.accountName;
    }
    if (message.totalBalance !== "") {
      obj.totalBalance = message.totalBalance;
    }
    if (message.creationDate !== undefined) {
      obj.creationDate = message.creationDate.toISOString();
    }
    if (message.updateDate !== undefined) {
      obj.updateDate = message.updateDate.toISOString();
    }
    if (message.currencyID !== "") {
      obj.currencyID = message.currencyID;
    }
    if (message.currencyInfo !== undefined) {
      obj.currencyInfo = Currency.toJSON(message.currencyInfo);
    }
    if (message.baseCurrencyValuation !== "") {
      obj.baseCurrencyValuation = message.baseCurrencyValuation;
    }
    return obj;
  },

  create(base?: DeepPartial<FiatProviderAccount>): FiatProviderAccount {
    return FiatProviderAccount.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FiatProviderAccount>): FiatProviderAccount {
    const message = createBaseFiatProviderAccount();
    message.id = object.id ?? "";
    message.provider = object.provider ?? "";
    message.label = object.label ?? "";
    message.accountType = object.accountType ?? "";
    message.accountIdentifier = object.accountIdentifier ?? "";
    message.accountName = object.accountName ?? "";
    message.totalBalance = object.totalBalance ?? "";
    message.creationDate = object.creationDate ?? undefined;
    message.updateDate = object.updateDate ?? undefined;
    message.currencyID = object.currencyID ?? "";
    message.currencyInfo = (object.currencyInfo !== undefined && object.currencyInfo !== null)
      ? Currency.fromPartial(object.currencyInfo)
      : undefined;
    message.baseCurrencyValuation = object.baseCurrencyValuation ?? "";
    return message;
  },
};

function createBaseFiatProviderCounterpartyAccount(): FiatProviderCounterpartyAccount {
  return {
    id: "",
    provider: "",
    label: "",
    accountType: "",
    accountIdentifier: "",
    accountName: "",
    counterpartyID: "",
    counterpartyName: "",
    creationDate: undefined,
    updateDate: undefined,
    currencyID: "",
    currencyInfo: undefined,
  };
}

export const FiatProviderCounterpartyAccount = {
  encode(message: FiatProviderCounterpartyAccount, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.provider !== "") {
      writer.uint32(18).string(message.provider);
    }
    if (message.label !== "") {
      writer.uint32(26).string(message.label);
    }
    if (message.accountType !== "") {
      writer.uint32(34).string(message.accountType);
    }
    if (message.accountIdentifier !== "") {
      writer.uint32(42).string(message.accountIdentifier);
    }
    if (message.accountName !== "") {
      writer.uint32(50).string(message.accountName);
    }
    if (message.counterpartyID !== "") {
      writer.uint32(58).string(message.counterpartyID);
    }
    if (message.counterpartyName !== "") {
      writer.uint32(66).string(message.counterpartyName);
    }
    if (message.creationDate !== undefined) {
      Timestamp.encode(toTimestamp(message.creationDate), writer.uint32(74).fork()).ldelim();
    }
    if (message.updateDate !== undefined) {
      Timestamp.encode(toTimestamp(message.updateDate), writer.uint32(82).fork()).ldelim();
    }
    if (message.currencyID !== "") {
      writer.uint32(90).string(message.currencyID);
    }
    if (message.currencyInfo !== undefined) {
      Currency.encode(message.currencyInfo, writer.uint32(98).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): FiatProviderCounterpartyAccount {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFiatProviderCounterpartyAccount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.provider = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.label = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.accountType = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.accountIdentifier = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.accountName = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.counterpartyID = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.counterpartyName = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.creationDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.updateDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.currencyID = reader.string();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.currencyInfo = Currency.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FiatProviderCounterpartyAccount {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      provider: isSet(object.provider) ? globalThis.String(object.provider) : "",
      label: isSet(object.label) ? globalThis.String(object.label) : "",
      accountType: isSet(object.accountType) ? globalThis.String(object.accountType) : "",
      accountIdentifier: isSet(object.accountIdentifier) ? globalThis.String(object.accountIdentifier) : "",
      accountName: isSet(object.accountName) ? globalThis.String(object.accountName) : "",
      counterpartyID: isSet(object.counterpartyID) ? globalThis.String(object.counterpartyID) : "",
      counterpartyName: isSet(object.counterpartyName) ? globalThis.String(object.counterpartyName) : "",
      creationDate: isSet(object.creationDate) ? fromJsonTimestamp(object.creationDate) : undefined,
      updateDate: isSet(object.updateDate) ? fromJsonTimestamp(object.updateDate) : undefined,
      currencyID: isSet(object.currencyID) ? globalThis.String(object.currencyID) : "",
      currencyInfo: isSet(object.currencyInfo) ? Currency.fromJSON(object.currencyInfo) : undefined,
    };
  },

  toJSON(message: FiatProviderCounterpartyAccount): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.provider !== "") {
      obj.provider = message.provider;
    }
    if (message.label !== "") {
      obj.label = message.label;
    }
    if (message.accountType !== "") {
      obj.accountType = message.accountType;
    }
    if (message.accountIdentifier !== "") {
      obj.accountIdentifier = message.accountIdentifier;
    }
    if (message.accountName !== "") {
      obj.accountName = message.accountName;
    }
    if (message.counterpartyID !== "") {
      obj.counterpartyID = message.counterpartyID;
    }
    if (message.counterpartyName !== "") {
      obj.counterpartyName = message.counterpartyName;
    }
    if (message.creationDate !== undefined) {
      obj.creationDate = message.creationDate.toISOString();
    }
    if (message.updateDate !== undefined) {
      obj.updateDate = message.updateDate.toISOString();
    }
    if (message.currencyID !== "") {
      obj.currencyID = message.currencyID;
    }
    if (message.currencyInfo !== undefined) {
      obj.currencyInfo = Currency.toJSON(message.currencyInfo);
    }
    return obj;
  },

  create(base?: DeepPartial<FiatProviderCounterpartyAccount>): FiatProviderCounterpartyAccount {
    return FiatProviderCounterpartyAccount.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FiatProviderCounterpartyAccount>): FiatProviderCounterpartyAccount {
    const message = createBaseFiatProviderCounterpartyAccount();
    message.id = object.id ?? "";
    message.provider = object.provider ?? "";
    message.label = object.label ?? "";
    message.accountType = object.accountType ?? "";
    message.accountIdentifier = object.accountIdentifier ?? "";
    message.accountName = object.accountName ?? "";
    message.counterpartyID = object.counterpartyID ?? "";
    message.counterpartyName = object.counterpartyName ?? "";
    message.creationDate = object.creationDate ?? undefined;
    message.updateDate = object.updateDate ?? undefined;
    message.currencyID = object.currencyID ?? "";
    message.currencyInfo = (object.currencyInfo !== undefined && object.currencyInfo !== null)
      ? Currency.fromPartial(object.currencyInfo)
      : undefined;
    return message;
  },
};

function createBaseFiatProvider(): FiatProvider {
  return { provider: "", label: "", baseCurrencyValuation: "" };
}

export const FiatProvider = {
  encode(message: FiatProvider, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.provider !== "") {
      writer.uint32(10).string(message.provider);
    }
    if (message.label !== "") {
      writer.uint32(18).string(message.label);
    }
    if (message.baseCurrencyValuation !== "") {
      writer.uint32(26).string(message.baseCurrencyValuation);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): FiatProvider {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFiatProvider();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.provider = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.label = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.baseCurrencyValuation = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FiatProvider {
    return {
      provider: isSet(object.provider) ? globalThis.String(object.provider) : "",
      label: isSet(object.label) ? globalThis.String(object.label) : "",
      baseCurrencyValuation: isSet(object.baseCurrencyValuation) ? globalThis.String(object.baseCurrencyValuation) : "",
    };
  },

  toJSON(message: FiatProvider): unknown {
    const obj: any = {};
    if (message.provider !== "") {
      obj.provider = message.provider;
    }
    if (message.label !== "") {
      obj.label = message.label;
    }
    if (message.baseCurrencyValuation !== "") {
      obj.baseCurrencyValuation = message.baseCurrencyValuation;
    }
    return obj;
  },

  create(base?: DeepPartial<FiatProvider>): FiatProvider {
    return FiatProvider.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FiatProvider>): FiatProvider {
    const message = createBaseFiatProvider();
    message.provider = object.provider ?? "";
    message.label = object.label ?? "";
    message.baseCurrencyValuation = object.baseCurrencyValuation ?? "";
    return message;
  },
};

function createBaseFiatProviderOperation(): FiatProviderOperation {
  return {
    id: "",
    provider: "",
    label: "",
    operationType: "",
    operationIdentifier: "",
    amount: "",
    creationDate: undefined,
    updateDate: undefined,
    currencyID: "",
    currencyInfo: undefined,
    operationDirection: "",
    fromAccountID: "",
    toAccountID: "",
    fromDetails: "",
    toDetails: "",
    status: "",
    comment: "",
    operationDetails: "",
  };
}

export const FiatProviderOperation = {
  encode(message: FiatProviderOperation, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.provider !== "") {
      writer.uint32(18).string(message.provider);
    }
    if (message.label !== "") {
      writer.uint32(26).string(message.label);
    }
    if (message.operationType !== "") {
      writer.uint32(34).string(message.operationType);
    }
    if (message.operationIdentifier !== "") {
      writer.uint32(42).string(message.operationIdentifier);
    }
    if (message.amount !== "") {
      writer.uint32(50).string(message.amount);
    }
    if (message.creationDate !== undefined) {
      Timestamp.encode(toTimestamp(message.creationDate), writer.uint32(58).fork()).ldelim();
    }
    if (message.updateDate !== undefined) {
      Timestamp.encode(toTimestamp(message.updateDate), writer.uint32(66).fork()).ldelim();
    }
    if (message.currencyID !== "") {
      writer.uint32(74).string(message.currencyID);
    }
    if (message.currencyInfo !== undefined) {
      Currency.encode(message.currencyInfo, writer.uint32(82).fork()).ldelim();
    }
    if (message.operationDirection !== "") {
      writer.uint32(90).string(message.operationDirection);
    }
    if (message.fromAccountID !== "") {
      writer.uint32(98).string(message.fromAccountID);
    }
    if (message.toAccountID !== "") {
      writer.uint32(106).string(message.toAccountID);
    }
    if (message.fromDetails !== "") {
      writer.uint32(114).string(message.fromDetails);
    }
    if (message.toDetails !== "") {
      writer.uint32(122).string(message.toDetails);
    }
    if (message.status !== "") {
      writer.uint32(130).string(message.status);
    }
    if (message.comment !== "") {
      writer.uint32(138).string(message.comment);
    }
    if (message.operationDetails !== "") {
      writer.uint32(146).string(message.operationDetails);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): FiatProviderOperation {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFiatProviderOperation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.provider = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.label = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.operationType = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.operationIdentifier = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.amount = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.creationDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.updateDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.currencyID = reader.string();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.currencyInfo = Currency.decode(reader, reader.uint32());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.operationDirection = reader.string();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.fromAccountID = reader.string();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.toAccountID = reader.string();
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.fromDetails = reader.string();
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.toDetails = reader.string();
          continue;
        case 16:
          if (tag !== 130) {
            break;
          }

          message.status = reader.string();
          continue;
        case 17:
          if (tag !== 138) {
            break;
          }

          message.comment = reader.string();
          continue;
        case 18:
          if (tag !== 146) {
            break;
          }

          message.operationDetails = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FiatProviderOperation {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      provider: isSet(object.provider) ? globalThis.String(object.provider) : "",
      label: isSet(object.label) ? globalThis.String(object.label) : "",
      operationType: isSet(object.operationType) ? globalThis.String(object.operationType) : "",
      operationIdentifier: isSet(object.operationIdentifier) ? globalThis.String(object.operationIdentifier) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      creationDate: isSet(object.creationDate) ? fromJsonTimestamp(object.creationDate) : undefined,
      updateDate: isSet(object.updateDate) ? fromJsonTimestamp(object.updateDate) : undefined,
      currencyID: isSet(object.currencyID) ? globalThis.String(object.currencyID) : "",
      currencyInfo: isSet(object.currencyInfo) ? Currency.fromJSON(object.currencyInfo) : undefined,
      operationDirection: isSet(object.operationDirection) ? globalThis.String(object.operationDirection) : "",
      fromAccountID: isSet(object.fromAccountID) ? globalThis.String(object.fromAccountID) : "",
      toAccountID: isSet(object.toAccountID) ? globalThis.String(object.toAccountID) : "",
      fromDetails: isSet(object.fromDetails) ? globalThis.String(object.fromDetails) : "",
      toDetails: isSet(object.toDetails) ? globalThis.String(object.toDetails) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      comment: isSet(object.comment) ? globalThis.String(object.comment) : "",
      operationDetails: isSet(object.operationDetails) ? globalThis.String(object.operationDetails) : "",
    };
  },

  toJSON(message: FiatProviderOperation): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.provider !== "") {
      obj.provider = message.provider;
    }
    if (message.label !== "") {
      obj.label = message.label;
    }
    if (message.operationType !== "") {
      obj.operationType = message.operationType;
    }
    if (message.operationIdentifier !== "") {
      obj.operationIdentifier = message.operationIdentifier;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.creationDate !== undefined) {
      obj.creationDate = message.creationDate.toISOString();
    }
    if (message.updateDate !== undefined) {
      obj.updateDate = message.updateDate.toISOString();
    }
    if (message.currencyID !== "") {
      obj.currencyID = message.currencyID;
    }
    if (message.currencyInfo !== undefined) {
      obj.currencyInfo = Currency.toJSON(message.currencyInfo);
    }
    if (message.operationDirection !== "") {
      obj.operationDirection = message.operationDirection;
    }
    if (message.fromAccountID !== "") {
      obj.fromAccountID = message.fromAccountID;
    }
    if (message.toAccountID !== "") {
      obj.toAccountID = message.toAccountID;
    }
    if (message.fromDetails !== "") {
      obj.fromDetails = message.fromDetails;
    }
    if (message.toDetails !== "") {
      obj.toDetails = message.toDetails;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.comment !== "") {
      obj.comment = message.comment;
    }
    if (message.operationDetails !== "") {
      obj.operationDetails = message.operationDetails;
    }
    return obj;
  },

  create(base?: DeepPartial<FiatProviderOperation>): FiatProviderOperation {
    return FiatProviderOperation.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FiatProviderOperation>): FiatProviderOperation {
    const message = createBaseFiatProviderOperation();
    message.id = object.id ?? "";
    message.provider = object.provider ?? "";
    message.label = object.label ?? "";
    message.operationType = object.operationType ?? "";
    message.operationIdentifier = object.operationIdentifier ?? "";
    message.amount = object.amount ?? "";
    message.creationDate = object.creationDate ?? undefined;
    message.updateDate = object.updateDate ?? undefined;
    message.currencyID = object.currencyID ?? "";
    message.currencyInfo = (object.currencyInfo !== undefined && object.currencyInfo !== null)
      ? Currency.fromPartial(object.currencyInfo)
      : undefined;
    message.operationDirection = object.operationDirection ?? "";
    message.fromAccountID = object.fromAccountID ?? "";
    message.toAccountID = object.toAccountID ?? "";
    message.fromDetails = object.fromDetails ?? "";
    message.toDetails = object.toDetails ?? "";
    message.status = object.status ?? "";
    message.comment = object.comment ?? "";
    message.operationDetails = object.operationDetails ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
