# coding: utf-8

"""
    Taurus-PROTECT APIs

    Taurus-PROTECT APIs description

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TgvalidatordUniqueCurrencyFilter(BaseModel):
    """
    TgvalidatordUniqueCurrencyFilter
    """ # noqa: E501
    blockchain: StrictStr = Field(description="Required: The Blockchain to filter by (e.g. ETH, BTC). Can be found using the blockchain endpoint `/api/rest/v1/blockchains`")
    network: StrictStr = Field(description="Required: Network or environment the currency is used on (e.g. 'mainnet', 'testnet').")
    token_contract_address: Optional[StrictStr] = Field(default=None, description="If this parameter is set, the currency returned will be a token with the specified contract address. If not set, the currency returned will be the native currency of the blockchain.", alias="tokenContractAddress")
    token_id: Optional[StrictStr] = Field(default=None, description="For some blockchains (ex. ALGO, XTZ) a tokenContractAddress might contain multiple assets. The tokenID is used to differentiate between those assets. If not set, the currency returned won't have any tokenID defined.", alias="tokenID")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["blockchain", "network", "tokenContractAddress", "tokenID"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TgvalidatordUniqueCurrencyFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TgvalidatordUniqueCurrencyFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "blockchain": obj.get("blockchain"),
            "network": obj.get("network"),
            "tokenContractAddress": obj.get("tokenContractAddress"),
            "tokenID": obj.get("tokenID")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


