/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScimServiceProviderConfigSort
 */
export interface ScimServiceProviderConfigSort {
    /**
     * 
     * @type {boolean}
     * @memberof ScimServiceProviderConfigSort
     */
    supported?: boolean;
    /**
     * Fields the server sent that this client does not know, kept so that decoding never fails
     * on them and serializing writes them back.
     * @type {object}
     * @memberof ScimServiceProviderConfigSort
     */
    additionalProperties?: { [key: string]: any };
}

const ScimServiceProviderConfigSortWireKeys: ReadonlySet<string> = new Set(['supported']);

/**
 * Check if a given object implements the ScimServiceProviderConfigSort interface.
 */
export function instanceOfScimServiceProviderConfigSort(value: object): value is ScimServiceProviderConfigSort {
    return true;
}

export function ScimServiceProviderConfigSortFromJSON(json: any): ScimServiceProviderConfigSort {
    return ScimServiceProviderConfigSortFromJSONTyped(json, false);
}

export function ScimServiceProviderConfigSortFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScimServiceProviderConfigSort {
    if (json == null) {
        return json;
    }
    const result: ScimServiceProviderConfigSort = {
        
        'supported': json['supported'] == null ? undefined : json['supported'],
    };
    const additionalProperties: { [key: string]: any } = {};
    for (const key of Object.keys(json)) {
        if (!ScimServiceProviderConfigSortWireKeys.has(key)) {
            additionalProperties[key] = json[key];
        }
    }
    if (Object.keys(additionalProperties).length > 0) {
        result.additionalProperties = additionalProperties;
    }
    return result;
}

  export function ScimServiceProviderConfigSortToJSON(json: any): ScimServiceProviderConfigSort {
      return ScimServiceProviderConfigSortToJSONTyped(json, false);
  }

  export function ScimServiceProviderConfigSortToJSONTyped(value?: ScimServiceProviderConfigSort | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'supported': value['supported'],
        ...value['additionalProperties'],
    };
}

