/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TgvalidatordKeyValue
 */
export interface TgvalidatordKeyValue {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordKeyValue
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordKeyValue
     */
    value?: string;
}

/**
 * Check if a given object implements the TgvalidatordKeyValue interface.
 */
export function instanceOfTgvalidatordKeyValue(value: object): value is TgvalidatordKeyValue {
    return true;
}

export function TgvalidatordKeyValueFromJSON(json: any): TgvalidatordKeyValue {
    return TgvalidatordKeyValueFromJSONTyped(json, false);
}

export function TgvalidatordKeyValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordKeyValue {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

  export function TgvalidatordKeyValueToJSON(json: any): TgvalidatordKeyValue {
      return TgvalidatordKeyValueToJSONTyped(json, false);
  }

  export function TgvalidatordKeyValueToJSONTyped(value?: TgvalidatordKeyValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

