/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TgvalidatordTnSettlementAssetTransfer } from './TgvalidatordTnSettlementAssetTransfer';
import {
    TgvalidatordTnSettlementAssetTransferFromJSON,
    TgvalidatordTnSettlementAssetTransferFromJSONTyped,
    TgvalidatordTnSettlementAssetTransferToJSON,
    TgvalidatordTnSettlementAssetTransferToJSONTyped,
} from './TgvalidatordTnSettlementAssetTransfer';
import type { CreateSettlementRequestClipRequest } from './CreateSettlementRequestClipRequest';
import {
    CreateSettlementRequestClipRequestFromJSON,
    CreateSettlementRequestClipRequestFromJSONTyped,
    CreateSettlementRequestClipRequestToJSON,
    CreateSettlementRequestClipRequestToJSONTyped,
} from './CreateSettlementRequestClipRequest';

/**
 * 
 * @export
 * @interface TgvalidatordCreateSettlementRequest
 */
export interface TgvalidatordCreateSettlementRequest {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordCreateSettlementRequest
     */
    targetParticipantID: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordCreateSettlementRequest
     */
    firstLegParticipantID: string;
    /**
     * 
     * @type {Array<TgvalidatordTnSettlementAssetTransfer>}
     * @memberof TgvalidatordCreateSettlementRequest
     */
    firstLegAssets: Array<TgvalidatordTnSettlementAssetTransfer>;
    /**
     * 
     * @type {Array<TgvalidatordTnSettlementAssetTransfer>}
     * @memberof TgvalidatordCreateSettlementRequest
     */
    secondLegAssets: Array<TgvalidatordTnSettlementAssetTransfer>;
    /**
     * 
     * @type {Array<CreateSettlementRequestClipRequest>}
     * @memberof TgvalidatordCreateSettlementRequest
     */
    clips?: Array<CreateSettlementRequestClipRequest>;
    /**
     * 
     * @type {Date}
     * @memberof TgvalidatordCreateSettlementRequest
     */
    startExecutionDate?: Date;
}

/**
 * Check if a given object implements the TgvalidatordCreateSettlementRequest interface.
 */
export function instanceOfTgvalidatordCreateSettlementRequest(value: object): value is TgvalidatordCreateSettlementRequest {
    if (!('targetParticipantID' in value) || value['targetParticipantID'] === undefined) return false;
    if (!('firstLegParticipantID' in value) || value['firstLegParticipantID'] === undefined) return false;
    if (!('firstLegAssets' in value) || value['firstLegAssets'] === undefined) return false;
    if (!('secondLegAssets' in value) || value['secondLegAssets'] === undefined) return false;
    return true;
}

export function TgvalidatordCreateSettlementRequestFromJSON(json: any): TgvalidatordCreateSettlementRequest {
    return TgvalidatordCreateSettlementRequestFromJSONTyped(json, false);
}

export function TgvalidatordCreateSettlementRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordCreateSettlementRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'targetParticipantID': json['targetParticipantID'],
        'firstLegParticipantID': json['firstLegParticipantID'],
        'firstLegAssets': ((json['firstLegAssets'] as Array<any>).map(TgvalidatordTnSettlementAssetTransferFromJSON)),
        'secondLegAssets': ((json['secondLegAssets'] as Array<any>).map(TgvalidatordTnSettlementAssetTransferFromJSON)),
        'clips': json['clips'] == null ? undefined : ((json['clips'] as Array<any>).map(CreateSettlementRequestClipRequestFromJSON)),
        'startExecutionDate': json['startExecutionDate'] == null ? undefined : (new Date(json['startExecutionDate'])),
    };
}

  export function TgvalidatordCreateSettlementRequestToJSON(json: any): TgvalidatordCreateSettlementRequest {
      return TgvalidatordCreateSettlementRequestToJSONTyped(json, false);
  }

  export function TgvalidatordCreateSettlementRequestToJSONTyped(value?: TgvalidatordCreateSettlementRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'targetParticipantID': value['targetParticipantID'],
        'firstLegParticipantID': value['firstLegParticipantID'],
        'firstLegAssets': ((value['firstLegAssets'] as Array<any>).map(TgvalidatordTnSettlementAssetTransferToJSON)),
        'secondLegAssets': ((value['secondLegAssets'] as Array<any>).map(TgvalidatordTnSettlementAssetTransferToJSON)),
        'clips': value['clips'] == null ? undefined : ((value['clips'] as Array<any>).map(CreateSettlementRequestClipRequestToJSON)),
        'startExecutionDate': value['startExecutionDate'] == null ? undefined : ((value['startExecutionDate']).toISOString()),
    };
}

