/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TgvalidatordApproversGroup
 */
export interface TgvalidatordApproversGroup {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordApproversGroup
     */
    externalGroupID?: string;
    /**
     * 
     * @type {number}
     * @memberof TgvalidatordApproversGroup
     */
    minimumSignatures?: number;
    /**
     * Fields the server sent that this client does not know, kept so that decoding never fails
     * on them and serializing writes them back.
     * @type {object}
     * @memberof TgvalidatordApproversGroup
     */
    additionalProperties?: { [key: string]: any };
}

const TgvalidatordApproversGroupWireKeys: ReadonlySet<string> = new Set(['externalGroupID', 'minimumSignatures']);

/**
 * Check if a given object implements the TgvalidatordApproversGroup interface.
 */
export function instanceOfTgvalidatordApproversGroup(value: object): value is TgvalidatordApproversGroup {
    return true;
}

export function TgvalidatordApproversGroupFromJSON(json: any): TgvalidatordApproversGroup {
    return TgvalidatordApproversGroupFromJSONTyped(json, false);
}

export function TgvalidatordApproversGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordApproversGroup {
    if (json == null) {
        return json;
    }
    const result: TgvalidatordApproversGroup = {
        
        'externalGroupID': json['externalGroupID'] == null ? undefined : json['externalGroupID'],
        'minimumSignatures': json['minimumSignatures'] == null ? undefined : json['minimumSignatures'],
    };
    const additionalProperties: { [key: string]: any } = {};
    for (const key of Object.keys(json)) {
        if (!TgvalidatordApproversGroupWireKeys.has(key)) {
            additionalProperties[key] = json[key];
        }
    }
    if (Object.keys(additionalProperties).length > 0) {
        result.additionalProperties = additionalProperties;
    }
    return result;
}

  export function TgvalidatordApproversGroupToJSON(json: any): TgvalidatordApproversGroup {
      return TgvalidatordApproversGroupToJSONTyped(json, false);
  }

  export function TgvalidatordApproversGroupToJSONTyped(value?: TgvalidatordApproversGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalGroupID': value['externalGroupID'],
        'minimumSignatures': value['minimumSignatures'],
        ...value['additionalProperties'],
    };
}

