/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TgvalidatordFeePayer } from './TgvalidatordFeePayer';
import {
    TgvalidatordFeePayerFromJSON,
    TgvalidatordFeePayerFromJSONTyped,
    TgvalidatordFeePayerToJSON,
    TgvalidatordFeePayerToJSONTyped,
} from './TgvalidatordFeePayer';

/**
 * 
 * @export
 * @interface TgvalidatordFeePayerEnvelope
 */
export interface TgvalidatordFeePayerEnvelope {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordFeePayerEnvelope
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordFeePayerEnvelope
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordFeePayerEnvelope
     */
    blockchain?: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordFeePayerEnvelope
     */
    name?: string;
    /**
     * 
     * @type {TgvalidatordFeePayer}
     * @memberof TgvalidatordFeePayerEnvelope
     */
    feePayer?: TgvalidatordFeePayer;
    /**
     * 
     * @type {Date}
     * @memberof TgvalidatordFeePayerEnvelope
     */
    creationDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordFeePayerEnvelope
     */
    network?: string;
    /**
     * Fields the server sent that this client does not know, kept so that decoding never fails
     * on them and serializing writes them back.
     * @type {object}
     * @memberof TgvalidatordFeePayerEnvelope
     */
    additionalProperties?: { [key: string]: any };
}

const TgvalidatordFeePayerEnvelopeWireKeys: ReadonlySet<string> = new Set(['id', 'tenantId', 'blockchain', 'name', 'feePayer', 'creationDate', 'network']);

/**
 * Check if a given object implements the TgvalidatordFeePayerEnvelope interface.
 */
export function instanceOfTgvalidatordFeePayerEnvelope(value: object): value is TgvalidatordFeePayerEnvelope {
    return true;
}

export function TgvalidatordFeePayerEnvelopeFromJSON(json: any): TgvalidatordFeePayerEnvelope {
    return TgvalidatordFeePayerEnvelopeFromJSONTyped(json, false);
}

export function TgvalidatordFeePayerEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordFeePayerEnvelope {
    if (json == null) {
        return json;
    }
    const result: TgvalidatordFeePayerEnvelope = {
        
        'id': json['id'] == null ? undefined : json['id'],
        'tenantId': json['tenantId'] == null ? undefined : json['tenantId'],
        'blockchain': json['blockchain'] == null ? undefined : json['blockchain'],
        'name': json['name'] == null ? undefined : json['name'],
        'feePayer': json['feePayer'] == null ? undefined : TgvalidatordFeePayerFromJSON(json['feePayer']),
        'creationDate': json['creationDate'] == null ? undefined : (new Date(json['creationDate'])),
        'network': json['network'] == null ? undefined : json['network'],
    };
    const additionalProperties: { [key: string]: any } = {};
    for (const key of Object.keys(json)) {
        if (!TgvalidatordFeePayerEnvelopeWireKeys.has(key)) {
            additionalProperties[key] = json[key];
        }
    }
    if (Object.keys(additionalProperties).length > 0) {
        result.additionalProperties = additionalProperties;
    }
    return result;
}

  export function TgvalidatordFeePayerEnvelopeToJSON(json: any): TgvalidatordFeePayerEnvelope {
      return TgvalidatordFeePayerEnvelopeToJSONTyped(json, false);
  }

  export function TgvalidatordFeePayerEnvelopeToJSONTyped(value?: TgvalidatordFeePayerEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'blockchain': value['blockchain'],
        'name': value['name'],
        'feePayer': TgvalidatordFeePayerToJSON(value['feePayer']),
        'creationDate': value['creationDate'] == null ? undefined : ((value['creationDate']).toISOString()),
        'network': value['network'],
        ...value['additionalProperties'],
    };
}

