/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TgvalidatordUpdateRulesProposalRequest
 */
export interface TgvalidatordUpdateRulesProposalRequest {
    /**
     * rulesContainer should respect base64 format.
     * @type {string}
     * @memberof TgvalidatordUpdateRulesProposalRequest
     */
    rulesContainer: string;
}

/**
 * Check if a given object implements the TgvalidatordUpdateRulesProposalRequest interface.
 */
export function instanceOfTgvalidatordUpdateRulesProposalRequest(value: object): value is TgvalidatordUpdateRulesProposalRequest {
    if (!('rulesContainer' in value) || value['rulesContainer'] === undefined) return false;
    return true;
}

export function TgvalidatordUpdateRulesProposalRequestFromJSON(json: any): TgvalidatordUpdateRulesProposalRequest {
    return TgvalidatordUpdateRulesProposalRequestFromJSONTyped(json, false);
}

export function TgvalidatordUpdateRulesProposalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordUpdateRulesProposalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rulesContainer': json['rulesContainer'],
    };
}

  export function TgvalidatordUpdateRulesProposalRequestToJSON(json: any): TgvalidatordUpdateRulesProposalRequest {
      return TgvalidatordUpdateRulesProposalRequestToJSONTyped(json, false);
  }

  export function TgvalidatordUpdateRulesProposalRequestToJSONTyped(value?: TgvalidatordUpdateRulesProposalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rulesContainer': value['rulesContainer'],
    };
}

