/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TgvalidatordCosmosMessageValueDestination
 */
export interface TgvalidatordCosmosMessageValueDestination {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordCosmosMessageValueDestination
     */
    addressId?: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordCosmosMessageValueDestination
     */
    whitelistedAddressId?: string;
}

/**
 * Check if a given object implements the TgvalidatordCosmosMessageValueDestination interface.
 */
export function instanceOfTgvalidatordCosmosMessageValueDestination(value: object): value is TgvalidatordCosmosMessageValueDestination {
    return true;
}

export function TgvalidatordCosmosMessageValueDestinationFromJSON(json: any): TgvalidatordCosmosMessageValueDestination {
    return TgvalidatordCosmosMessageValueDestinationFromJSONTyped(json, false);
}

export function TgvalidatordCosmosMessageValueDestinationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordCosmosMessageValueDestination {
    if (json == null) {
        return json;
    }
    return {
        
        'addressId': json['addressId'] == null ? undefined : json['addressId'],
        'whitelistedAddressId': json['whitelistedAddressId'] == null ? undefined : json['whitelistedAddressId'],
    };
}

  export function TgvalidatordCosmosMessageValueDestinationToJSON(json: any): TgvalidatordCosmosMessageValueDestination {
      return TgvalidatordCosmosMessageValueDestinationToJSONTyped(json, false);
  }

  export function TgvalidatordCosmosMessageValueDestinationToJSONTyped(value?: TgvalidatordCosmosMessageValueDestination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addressId': value['addressId'],
        'whitelistedAddressId': value['whitelistedAddressId'],
    };
}

