/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TgvalidatordSAMLInitiateRequest
 */
export interface TgvalidatordSAMLInitiateRequest {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordSAMLInitiateRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordSAMLInitiateRequest
     */
    redirectUri: string;
    /**
     * Fields the server sent that this client does not know, kept so that decoding never fails
     * on them and serializing writes them back.
     * @type {object}
     * @memberof TgvalidatordSAMLInitiateRequest
     */
    additionalProperties?: { [key: string]: any };
}

const TgvalidatordSAMLInitiateRequestWireKeys: ReadonlySet<string> = new Set(['email', 'redirectUri']);

/**
 * Check if a given object implements the TgvalidatordSAMLInitiateRequest interface.
 */
export function instanceOfTgvalidatordSAMLInitiateRequest(value: object): value is TgvalidatordSAMLInitiateRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('redirectUri' in value) || value['redirectUri'] === undefined) return false;
    return true;
}

export function TgvalidatordSAMLInitiateRequestFromJSON(json: any): TgvalidatordSAMLInitiateRequest {
    return TgvalidatordSAMLInitiateRequestFromJSONTyped(json, false);
}

export function TgvalidatordSAMLInitiateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordSAMLInitiateRequest {
    if (json == null) {
        return json;
    }
    const result: TgvalidatordSAMLInitiateRequest = {
        
        'email': json['email'],
        'redirectUri': json['redirectUri'],
    };
    const additionalProperties: { [key: string]: any } = {};
    for (const key of Object.keys(json)) {
        if (!TgvalidatordSAMLInitiateRequestWireKeys.has(key)) {
            additionalProperties[key] = json[key];
        }
    }
    if (Object.keys(additionalProperties).length > 0) {
        result.additionalProperties = additionalProperties;
    }
    return result;
}

  export function TgvalidatordSAMLInitiateRequestToJSON(json: any): TgvalidatordSAMLInitiateRequest {
      return TgvalidatordSAMLInitiateRequestToJSONTyped(json, false);
  }

  export function TgvalidatordSAMLInitiateRequestToJSONTyped(value?: TgvalidatordSAMLInitiateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'redirectUri': value['redirectUri'],
        ...value['additionalProperties'],
    };
}

