/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TgvalidatordCreateChangeResult
 */
export interface TgvalidatordCreateChangeResult {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordCreateChangeResult
     */
    id?: string;
    /**
     * Fields the server sent that this client does not know, kept so that decoding never fails
     * on them and serializing writes them back.
     * @type {object}
     * @memberof TgvalidatordCreateChangeResult
     */
    additionalProperties?: { [key: string]: any };
}

const TgvalidatordCreateChangeResultWireKeys: ReadonlySet<string> = new Set(['id']);

/**
 * Check if a given object implements the TgvalidatordCreateChangeResult interface.
 */
export function instanceOfTgvalidatordCreateChangeResult(value: object): value is TgvalidatordCreateChangeResult {
    return true;
}

export function TgvalidatordCreateChangeResultFromJSON(json: any): TgvalidatordCreateChangeResult {
    return TgvalidatordCreateChangeResultFromJSONTyped(json, false);
}

export function TgvalidatordCreateChangeResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordCreateChangeResult {
    if (json == null) {
        return json;
    }
    const result: TgvalidatordCreateChangeResult = {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
    const additionalProperties: { [key: string]: any } = {};
    for (const key of Object.keys(json)) {
        if (!TgvalidatordCreateChangeResultWireKeys.has(key)) {
            additionalProperties[key] = json[key];
        }
    }
    if (Object.keys(additionalProperties).length > 0) {
        result.additionalProperties = additionalProperties;
    }
    return result;
}

  export function TgvalidatordCreateChangeResultToJSON(json: any): TgvalidatordCreateChangeResult {
      return TgvalidatordCreateChangeResultToJSONTyped(json, false);
  }

  export function TgvalidatordCreateChangeResultToJSONTyped(value?: TgvalidatordCreateChangeResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        ...value['additionalProperties'],
    };
}

