/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TgvalidatordJob } from './TgvalidatordJob';
import {
    TgvalidatordJobFromJSON,
    TgvalidatordJobFromJSONTyped,
    TgvalidatordJobToJSON,
    TgvalidatordJobToJSONTyped,
} from './TgvalidatordJob';

/**
 * 
 * @export
 * @interface TgvalidatordGetJobsReply
 */
export interface TgvalidatordGetJobsReply {
    /**
     * 
     * @type {Array<TgvalidatordJob>}
     * @memberof TgvalidatordGetJobsReply
     */
    jobs?: Array<TgvalidatordJob>;
}

/**
 * Check if a given object implements the TgvalidatordGetJobsReply interface.
 */
export function instanceOfTgvalidatordGetJobsReply(value: object): value is TgvalidatordGetJobsReply {
    return true;
}

export function TgvalidatordGetJobsReplyFromJSON(json: any): TgvalidatordGetJobsReply {
    return TgvalidatordGetJobsReplyFromJSONTyped(json, false);
}

export function TgvalidatordGetJobsReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordGetJobsReply {
    if (json == null) {
        return json;
    }
    return {
        
        'jobs': json['jobs'] == null ? undefined : ((json['jobs'] as Array<any>).map(TgvalidatordJobFromJSON)),
    };
}

  export function TgvalidatordGetJobsReplyToJSON(json: any): TgvalidatordGetJobsReply {
      return TgvalidatordGetJobsReplyToJSONTyped(json, false);
  }

  export function TgvalidatordGetJobsReplyToJSONTyped(value?: TgvalidatordGetJobsReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobs': value['jobs'] == null ? undefined : ((value['jobs'] as Array<any>).map(TgvalidatordJobToJSON)),
    };
}

