/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TgvalidatordRequestAttribute
 */
export interface TgvalidatordRequestAttribute {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordRequestAttribute
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordRequestAttribute
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordRequestAttribute
     */
    value?: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordRequestAttribute
     */
    contentType?: string;
    /**
     * Fields the server sent that this client does not know, kept so that decoding never fails
     * on them and serializing writes them back.
     * @type {object}
     * @memberof TgvalidatordRequestAttribute
     */
    additionalProperties?: { [key: string]: any };
}

const TgvalidatordRequestAttributeWireKeys: ReadonlySet<string> = new Set(['id', 'key', 'value', 'contentType']);

/**
 * Check if a given object implements the TgvalidatordRequestAttribute interface.
 */
export function instanceOfTgvalidatordRequestAttribute(value: object): value is TgvalidatordRequestAttribute {
    return true;
}

export function TgvalidatordRequestAttributeFromJSON(json: any): TgvalidatordRequestAttribute {
    return TgvalidatordRequestAttributeFromJSONTyped(json, false);
}

export function TgvalidatordRequestAttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordRequestAttribute {
    if (json == null) {
        return json;
    }
    const result: TgvalidatordRequestAttribute = {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
    };
    const additionalProperties: { [key: string]: any } = {};
    for (const key of Object.keys(json)) {
        if (!TgvalidatordRequestAttributeWireKeys.has(key)) {
            additionalProperties[key] = json[key];
        }
    }
    if (Object.keys(additionalProperties).length > 0) {
        result.additionalProperties = additionalProperties;
    }
    return result;
}

  export function TgvalidatordRequestAttributeToJSON(json: any): TgvalidatordRequestAttribute {
      return TgvalidatordRequestAttributeToJSONTyped(json, false);
  }

  export function TgvalidatordRequestAttributeToJSONTyped(value?: TgvalidatordRequestAttribute | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'value': value['value'],
        'contentType': value['contentType'],
        ...value['additionalProperties'],
    };
}

