/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TgvalidatordInternalAddressDetails
 */
export interface TgvalidatordInternalAddressDetails {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordInternalAddressDetails
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordInternalAddressDetails
     */
    blockchainAddressID?: string;
}

/**
 * Check if a given object implements the TgvalidatordInternalAddressDetails interface.
 */
export function instanceOfTgvalidatordInternalAddressDetails(value: object): value is TgvalidatordInternalAddressDetails {
    return true;
}

export function TgvalidatordInternalAddressDetailsFromJSON(json: any): TgvalidatordInternalAddressDetails {
    return TgvalidatordInternalAddressDetailsFromJSONTyped(json, false);
}

export function TgvalidatordInternalAddressDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordInternalAddressDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'blockchainAddressID': json['blockchainAddressID'] == null ? undefined : json['blockchainAddressID'],
    };
}

  export function TgvalidatordInternalAddressDetailsToJSON(json: any): TgvalidatordInternalAddressDetails {
      return TgvalidatordInternalAddressDetailsToJSONTyped(json, false);
  }

  export function TgvalidatordInternalAddressDetailsToJSONTyped(value?: TgvalidatordInternalAddressDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'blockchainAddressID': value['blockchainAddressID'],
    };
}

