/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TgvalidatordOIDCSession
 */
export interface TgvalidatordOIDCSession {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordOIDCSession
     */
    token?: string;
    /**
     * Fields the server sent that this client does not know, kept so that decoding never fails
     * on them and serializing writes them back.
     * @type {object}
     * @memberof TgvalidatordOIDCSession
     */
    additionalProperties?: { [key: string]: any };
}

const TgvalidatordOIDCSessionWireKeys: ReadonlySet<string> = new Set(['token']);

/**
 * Check if a given object implements the TgvalidatordOIDCSession interface.
 */
export function instanceOfTgvalidatordOIDCSession(value: object): value is TgvalidatordOIDCSession {
    return true;
}

export function TgvalidatordOIDCSessionFromJSON(json: any): TgvalidatordOIDCSession {
    return TgvalidatordOIDCSessionFromJSONTyped(json, false);
}

export function TgvalidatordOIDCSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordOIDCSession {
    if (json == null) {
        return json;
    }
    const result: TgvalidatordOIDCSession = {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
    const additionalProperties: { [key: string]: any } = {};
    for (const key of Object.keys(json)) {
        if (!TgvalidatordOIDCSessionWireKeys.has(key)) {
            additionalProperties[key] = json[key];
        }
    }
    if (Object.keys(additionalProperties).length > 0) {
        result.additionalProperties = additionalProperties;
    }
    return result;
}

  export function TgvalidatordOIDCSessionToJSON(json: any): TgvalidatordOIDCSession {
      return TgvalidatordOIDCSessionToJSONTyped(json, false);
  }

  export function TgvalidatordOIDCSessionToJSONTyped(value?: TgvalidatordOIDCSession | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        ...value['additionalProperties'],
    };
}

