/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TgvalidatordPricesHistoryPoint } from './TgvalidatordPricesHistoryPoint';
import {
    TgvalidatordPricesHistoryPointFromJSON,
    TgvalidatordPricesHistoryPointFromJSONTyped,
    TgvalidatordPricesHistoryPointToJSON,
    TgvalidatordPricesHistoryPointToJSONTyped,
} from './TgvalidatordPricesHistoryPoint';

/**
 * 
 * @export
 * @interface TgvalidatordGetPricesHistoryReply
 */
export interface TgvalidatordGetPricesHistoryReply {
    /**
     * 
     * @type {Array<TgvalidatordPricesHistoryPoint>}
     * @memberof TgvalidatordGetPricesHistoryReply
     */
    result?: Array<TgvalidatordPricesHistoryPoint>;
    /**
     * Period between the points of the history. See https://golang.org/pkg/time/#Duration.String for the format.
     * @type {string}
     * @memberof TgvalidatordGetPricesHistoryReply
     */
    period?: string;
}

/**
 * Check if a given object implements the TgvalidatordGetPricesHistoryReply interface.
 */
export function instanceOfTgvalidatordGetPricesHistoryReply(value: object): value is TgvalidatordGetPricesHistoryReply {
    return true;
}

export function TgvalidatordGetPricesHistoryReplyFromJSON(json: any): TgvalidatordGetPricesHistoryReply {
    return TgvalidatordGetPricesHistoryReplyFromJSONTyped(json, false);
}

export function TgvalidatordGetPricesHistoryReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordGetPricesHistoryReply {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(TgvalidatordPricesHistoryPointFromJSON)),
        'period': json['period'] == null ? undefined : json['period'],
    };
}

  export function TgvalidatordGetPricesHistoryReplyToJSON(json: any): TgvalidatordGetPricesHistoryReply {
      return TgvalidatordGetPricesHistoryReplyToJSONTyped(json, false);
  }

  export function TgvalidatordGetPricesHistoryReplyToJSONTyped(value?: TgvalidatordGetPricesHistoryReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(TgvalidatordPricesHistoryPointToJSON)),
        'period': value['period'],
    };
}

