/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TgvalidatordExportTransactionTravelRuleReply
 */
export interface TgvalidatordExportTransactionTravelRuleReply {
    /**
     * 
     * @type {string}
     * @memberof TgvalidatordExportTransactionTravelRuleReply
     */
    result?: string;
}

/**
 * Check if a given object implements the TgvalidatordExportTransactionTravelRuleReply interface.
 */
export function instanceOfTgvalidatordExportTransactionTravelRuleReply(value: object): value is TgvalidatordExportTransactionTravelRuleReply {
    return true;
}

export function TgvalidatordExportTransactionTravelRuleReplyFromJSON(json: any): TgvalidatordExportTransactionTravelRuleReply {
    return TgvalidatordExportTransactionTravelRuleReplyFromJSONTyped(json, false);
}

export function TgvalidatordExportTransactionTravelRuleReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TgvalidatordExportTransactionTravelRuleReply {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : json['result'],
    };
}

  export function TgvalidatordExportTransactionTravelRuleReplyToJSON(json: any): TgvalidatordExportTransactionTravelRuleReply {
      return TgvalidatordExportTransactionTravelRuleReplyToJSONTyped(json, false);
  }

  export function TgvalidatordExportTransactionTravelRuleReplyToJSONTyped(value?: TgvalidatordExportTransactionTravelRuleReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
    };
}

