/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ScimServiceScimPatchUserBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScimServiceScimPatchUserBody{}

// ScimServiceScimPatchUserBody struct for ScimServiceScimPatchUserBody
type ScimServiceScimPatchUserBody struct {
	Schemas []string `json:"schemas,omitempty"`
	Operations []TgvalidatordScimOperation `json:"Operations,omitempty"`
}

// NewScimServiceScimPatchUserBody instantiates a new ScimServiceScimPatchUserBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScimServiceScimPatchUserBody() *ScimServiceScimPatchUserBody {
	this := ScimServiceScimPatchUserBody{}
	return &this
}

// NewScimServiceScimPatchUserBodyWithDefaults instantiates a new ScimServiceScimPatchUserBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimServiceScimPatchUserBodyWithDefaults() *ScimServiceScimPatchUserBody {
	this := ScimServiceScimPatchUserBody{}
	return &this
}

// GetSchemas returns the Schemas field value if set, zero value otherwise.
func (o *ScimServiceScimPatchUserBody) GetSchemas() []string {
	if o == nil || IsNil(o.Schemas) {
		var ret []string
		return ret
	}
	return o.Schemas
}

// GetSchemasOk returns a tuple with the Schemas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimServiceScimPatchUserBody) GetSchemasOk() ([]string, bool) {
	if o == nil || IsNil(o.Schemas) {
		return nil, false
	}
	return o.Schemas, true
}

// HasSchemas returns a boolean if a field has been set.
func (o *ScimServiceScimPatchUserBody) HasSchemas() bool {
	if o != nil && !IsNil(o.Schemas) {
		return true
	}

	return false
}

// SetSchemas gets a reference to the given []string and assigns it to the Schemas field.
func (o *ScimServiceScimPatchUserBody) SetSchemas(v []string) {
	o.Schemas = v
}

// GetOperations returns the Operations field value if set, zero value otherwise.
func (o *ScimServiceScimPatchUserBody) GetOperations() []TgvalidatordScimOperation {
	if o == nil || IsNil(o.Operations) {
		var ret []TgvalidatordScimOperation
		return ret
	}
	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimServiceScimPatchUserBody) GetOperationsOk() ([]TgvalidatordScimOperation, bool) {
	if o == nil || IsNil(o.Operations) {
		return nil, false
	}
	return o.Operations, true
}

// HasOperations returns a boolean if a field has been set.
func (o *ScimServiceScimPatchUserBody) HasOperations() bool {
	if o != nil && !IsNil(o.Operations) {
		return true
	}

	return false
}

// SetOperations gets a reference to the given []TgvalidatordScimOperation and assigns it to the Operations field.
func (o *ScimServiceScimPatchUserBody) SetOperations(v []TgvalidatordScimOperation) {
	o.Operations = v
}

func (o ScimServiceScimPatchUserBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScimServiceScimPatchUserBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schemas) {
		toSerialize["schemas"] = o.Schemas
	}
	if !IsNil(o.Operations) {
		toSerialize["Operations"] = o.Operations
	}
	return toSerialize, nil
}

type NullableScimServiceScimPatchUserBody struct {
	value *ScimServiceScimPatchUserBody
	isSet bool
}

func (v NullableScimServiceScimPatchUserBody) Get() *ScimServiceScimPatchUserBody {
	return v.value
}

func (v *NullableScimServiceScimPatchUserBody) Set(val *ScimServiceScimPatchUserBody) {
	v.value = val
	v.isSet = true
}

func (v NullableScimServiceScimPatchUserBody) IsSet() bool {
	return v.isSet
}

func (v *NullableScimServiceScimPatchUserBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimServiceScimPatchUserBody(val *ScimServiceScimPatchUserBody) *NullableScimServiceScimPatchUserBody {
	return &NullableScimServiceScimPatchUserBody{value: val, isSet: true}
}

func (v NullableScimServiceScimPatchUserBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimServiceScimPatchUserBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


