/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the TgvalidatordAuditTrail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TgvalidatordAuditTrail{}

// TgvalidatordAuditTrail struct for TgvalidatordAuditTrail
type TgvalidatordAuditTrail struct {
	Id *string `json:"id,omitempty"`
	User *TgvalidatordUserInfo `json:"user,omitempty"`
	Entity *string `json:"entity,omitempty"`
	Action *string `json:"action,omitempty"`
	SubAction *string `json:"subAction,omitempty"`
	Details *string `json:"details,omitempty"`
	CreationDate *time.Time `json:"creationDate,omitempty"`
}

// NewTgvalidatordAuditTrail instantiates a new TgvalidatordAuditTrail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTgvalidatordAuditTrail() *TgvalidatordAuditTrail {
	this := TgvalidatordAuditTrail{}
	return &this
}

// NewTgvalidatordAuditTrailWithDefaults instantiates a new TgvalidatordAuditTrail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTgvalidatordAuditTrailWithDefaults() *TgvalidatordAuditTrail {
	this := TgvalidatordAuditTrail{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TgvalidatordAuditTrail) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordAuditTrail) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TgvalidatordAuditTrail) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TgvalidatordAuditTrail) SetId(v string) {
	o.Id = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *TgvalidatordAuditTrail) GetUser() TgvalidatordUserInfo {
	if o == nil || IsNil(o.User) {
		var ret TgvalidatordUserInfo
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordAuditTrail) GetUserOk() (*TgvalidatordUserInfo, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *TgvalidatordAuditTrail) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given TgvalidatordUserInfo and assigns it to the User field.
func (o *TgvalidatordAuditTrail) SetUser(v TgvalidatordUserInfo) {
	o.User = &v
}

// GetEntity returns the Entity field value if set, zero value otherwise.
func (o *TgvalidatordAuditTrail) GetEntity() string {
	if o == nil || IsNil(o.Entity) {
		var ret string
		return ret
	}
	return *o.Entity
}

// GetEntityOk returns a tuple with the Entity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordAuditTrail) GetEntityOk() (*string, bool) {
	if o == nil || IsNil(o.Entity) {
		return nil, false
	}
	return o.Entity, true
}

// HasEntity returns a boolean if a field has been set.
func (o *TgvalidatordAuditTrail) HasEntity() bool {
	if o != nil && !IsNil(o.Entity) {
		return true
	}

	return false
}

// SetEntity gets a reference to the given string and assigns it to the Entity field.
func (o *TgvalidatordAuditTrail) SetEntity(v string) {
	o.Entity = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *TgvalidatordAuditTrail) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordAuditTrail) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *TgvalidatordAuditTrail) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *TgvalidatordAuditTrail) SetAction(v string) {
	o.Action = &v
}

// GetSubAction returns the SubAction field value if set, zero value otherwise.
func (o *TgvalidatordAuditTrail) GetSubAction() string {
	if o == nil || IsNil(o.SubAction) {
		var ret string
		return ret
	}
	return *o.SubAction
}

// GetSubActionOk returns a tuple with the SubAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordAuditTrail) GetSubActionOk() (*string, bool) {
	if o == nil || IsNil(o.SubAction) {
		return nil, false
	}
	return o.SubAction, true
}

// HasSubAction returns a boolean if a field has been set.
func (o *TgvalidatordAuditTrail) HasSubAction() bool {
	if o != nil && !IsNil(o.SubAction) {
		return true
	}

	return false
}

// SetSubAction gets a reference to the given string and assigns it to the SubAction field.
func (o *TgvalidatordAuditTrail) SetSubAction(v string) {
	o.SubAction = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *TgvalidatordAuditTrail) GetDetails() string {
	if o == nil || IsNil(o.Details) {
		var ret string
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordAuditTrail) GetDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *TgvalidatordAuditTrail) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given string and assigns it to the Details field.
func (o *TgvalidatordAuditTrail) SetDetails(v string) {
	o.Details = &v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *TgvalidatordAuditTrail) GetCreationDate() time.Time {
	if o == nil || IsNil(o.CreationDate) {
		var ret time.Time
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordAuditTrail) GetCreationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *TgvalidatordAuditTrail) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given time.Time and assigns it to the CreationDate field.
func (o *TgvalidatordAuditTrail) SetCreationDate(v time.Time) {
	o.CreationDate = &v
}

func (o TgvalidatordAuditTrail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TgvalidatordAuditTrail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Entity) {
		toSerialize["entity"] = o.Entity
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.SubAction) {
		toSerialize["subAction"] = o.SubAction
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	if !IsNil(o.CreationDate) {
		toSerialize["creationDate"] = o.CreationDate
	}
	return toSerialize, nil
}

type NullableTgvalidatordAuditTrail struct {
	value *TgvalidatordAuditTrail
	isSet bool
}

func (v NullableTgvalidatordAuditTrail) Get() *TgvalidatordAuditTrail {
	return v.value
}

func (v *NullableTgvalidatordAuditTrail) Set(val *TgvalidatordAuditTrail) {
	v.value = val
	v.isSet = true
}

func (v NullableTgvalidatordAuditTrail) IsSet() bool {
	return v.isSet
}

func (v *NullableTgvalidatordAuditTrail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTgvalidatordAuditTrail(val *TgvalidatordAuditTrail) *NullableTgvalidatordAuditTrail {
	return &NullableTgvalidatordAuditTrail{value: val, isSet: true}
}

func (v NullableTgvalidatordAuditTrail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTgvalidatordAuditTrail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


