/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the TgvalidatordRevealUserApiKeyReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TgvalidatordRevealUserApiKeyReply{}

// TgvalidatordRevealUserApiKeyReply struct for TgvalidatordRevealUserApiKeyReply
type TgvalidatordRevealUserApiKeyReply struct {
	ApiKeyId *string `json:"apiKeyId,omitempty"`
	Secret *string `json:"secret,omitempty"`
	CreationDate *time.Time `json:"creationDate,omitempty"`
	RevealDate *time.Time `json:"revealDate,omitempty"`
	Revealable *bool `json:"revealable,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TgvalidatordRevealUserApiKeyReply TgvalidatordRevealUserApiKeyReply

// NewTgvalidatordRevealUserApiKeyReply instantiates a new TgvalidatordRevealUserApiKeyReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTgvalidatordRevealUserApiKeyReply() *TgvalidatordRevealUserApiKeyReply {
	this := TgvalidatordRevealUserApiKeyReply{}
	return &this
}

// NewTgvalidatordRevealUserApiKeyReplyWithDefaults instantiates a new TgvalidatordRevealUserApiKeyReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTgvalidatordRevealUserApiKeyReplyWithDefaults() *TgvalidatordRevealUserApiKeyReply {
	this := TgvalidatordRevealUserApiKeyReply{}
	return &this
}

// GetApiKeyId returns the ApiKeyId field value if set, zero value otherwise.
func (o *TgvalidatordRevealUserApiKeyReply) GetApiKeyId() string {
	if o == nil || IsNil(o.ApiKeyId) {
		var ret string
		return ret
	}
	return *o.ApiKeyId
}

// GetApiKeyIdOk returns a tuple with the ApiKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordRevealUserApiKeyReply) GetApiKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.ApiKeyId) {
		return nil, false
	}
	return o.ApiKeyId, true
}

// HasApiKeyId returns a boolean if a field has been set.
func (o *TgvalidatordRevealUserApiKeyReply) HasApiKeyId() bool {
	if o != nil && !IsNil(o.ApiKeyId) {
		return true
	}

	return false
}

// SetApiKeyId gets a reference to the given string and assigns it to the ApiKeyId field.
func (o *TgvalidatordRevealUserApiKeyReply) SetApiKeyId(v string) {
	o.ApiKeyId = &v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *TgvalidatordRevealUserApiKeyReply) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordRevealUserApiKeyReply) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *TgvalidatordRevealUserApiKeyReply) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *TgvalidatordRevealUserApiKeyReply) SetSecret(v string) {
	o.Secret = &v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *TgvalidatordRevealUserApiKeyReply) GetCreationDate() time.Time {
	if o == nil || IsNil(o.CreationDate) {
		var ret time.Time
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordRevealUserApiKeyReply) GetCreationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *TgvalidatordRevealUserApiKeyReply) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given time.Time and assigns it to the CreationDate field.
func (o *TgvalidatordRevealUserApiKeyReply) SetCreationDate(v time.Time) {
	o.CreationDate = &v
}

// GetRevealDate returns the RevealDate field value if set, zero value otherwise.
func (o *TgvalidatordRevealUserApiKeyReply) GetRevealDate() time.Time {
	if o == nil || IsNil(o.RevealDate) {
		var ret time.Time
		return ret
	}
	return *o.RevealDate
}

// GetRevealDateOk returns a tuple with the RevealDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordRevealUserApiKeyReply) GetRevealDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RevealDate) {
		return nil, false
	}
	return o.RevealDate, true
}

// HasRevealDate returns a boolean if a field has been set.
func (o *TgvalidatordRevealUserApiKeyReply) HasRevealDate() bool {
	if o != nil && !IsNil(o.RevealDate) {
		return true
	}

	return false
}

// SetRevealDate gets a reference to the given time.Time and assigns it to the RevealDate field.
func (o *TgvalidatordRevealUserApiKeyReply) SetRevealDate(v time.Time) {
	o.RevealDate = &v
}

// GetRevealable returns the Revealable field value if set, zero value otherwise.
func (o *TgvalidatordRevealUserApiKeyReply) GetRevealable() bool {
	if o == nil || IsNil(o.Revealable) {
		var ret bool
		return ret
	}
	return *o.Revealable
}

// GetRevealableOk returns a tuple with the Revealable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordRevealUserApiKeyReply) GetRevealableOk() (*bool, bool) {
	if o == nil || IsNil(o.Revealable) {
		return nil, false
	}
	return o.Revealable, true
}

// HasRevealable returns a boolean if a field has been set.
func (o *TgvalidatordRevealUserApiKeyReply) HasRevealable() bool {
	if o != nil && !IsNil(o.Revealable) {
		return true
	}

	return false
}

// SetRevealable gets a reference to the given bool and assigns it to the Revealable field.
func (o *TgvalidatordRevealUserApiKeyReply) SetRevealable(v bool) {
	o.Revealable = &v
}

func (o TgvalidatordRevealUserApiKeyReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TgvalidatordRevealUserApiKeyReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiKeyId) {
		toSerialize["apiKeyId"] = o.ApiKeyId
	}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	if !IsNil(o.CreationDate) {
		toSerialize["creationDate"] = o.CreationDate
	}
	if !IsNil(o.RevealDate) {
		toSerialize["revealDate"] = o.RevealDate
	}
	if !IsNil(o.Revealable) {
		toSerialize["revealable"] = o.Revealable
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TgvalidatordRevealUserApiKeyReply) UnmarshalJSON(data []byte) (err error) {
	varTgvalidatordRevealUserApiKeyReply := _TgvalidatordRevealUserApiKeyReply{}

	err = json.Unmarshal(data, &varTgvalidatordRevealUserApiKeyReply)

	if err != nil {
		return err
	}

	*o = TgvalidatordRevealUserApiKeyReply(varTgvalidatordRevealUserApiKeyReply)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "apiKeyId")
		delete(additionalProperties, "secret")
		delete(additionalProperties, "creationDate")
		delete(additionalProperties, "revealDate")
		delete(additionalProperties, "revealable")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTgvalidatordRevealUserApiKeyReply struct {
	value *TgvalidatordRevealUserApiKeyReply
	isSet bool
}

func (v NullableTgvalidatordRevealUserApiKeyReply) Get() *TgvalidatordRevealUserApiKeyReply {
	return v.value
}

func (v *NullableTgvalidatordRevealUserApiKeyReply) Set(val *TgvalidatordRevealUserApiKeyReply) {
	v.value = val
	v.isSet = true
}

func (v NullableTgvalidatordRevealUserApiKeyReply) IsSet() bool {
	return v.isSet
}

func (v *NullableTgvalidatordRevealUserApiKeyReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTgvalidatordRevealUserApiKeyReply(val *TgvalidatordRevealUserApiKeyReply) *NullableTgvalidatordRevealUserApiKeyReply {
	return &NullableTgvalidatordRevealUserApiKeyReply{value: val, isSet: true}
}

func (v NullableTgvalidatordRevealUserApiKeyReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTgvalidatordRevealUserApiKeyReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


