/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// GetICPNeuronInfoReplyNeuronState the model 'GetICPNeuronInfoReplyNeuronState'
type GetICPNeuronInfoReplyNeuronState string

// List of GetICPNeuronInfoReplyNeuronState
const (
	GETICPNEURONINFOREPLYNEURONSTATE_NEURON_STATE_NOT_DISSOLVING GetICPNeuronInfoReplyNeuronState = "NeuronStateNotDissolving"
	GETICPNEURONINFOREPLYNEURONSTATE_NEURON_STATE_DISSOLVING GetICPNeuronInfoReplyNeuronState = "NeuronStateDissolving"
	GETICPNEURONINFOREPLYNEURONSTATE_NEURON_STATE_DISSOLVED GetICPNeuronInfoReplyNeuronState = "NeuronStateDissolved"
	GETICPNEURONINFOREPLYNEURONSTATE_NEURON_STATE_SPAWNING GetICPNeuronInfoReplyNeuronState = "NeuronStateSpawning"
)

// All allowed values of GetICPNeuronInfoReplyNeuronState enum
var AllowedGetICPNeuronInfoReplyNeuronStateEnumValues = []GetICPNeuronInfoReplyNeuronState{
	"NeuronStateNotDissolving",
	"NeuronStateDissolving",
	"NeuronStateDissolved",
	"NeuronStateSpawning",
}

func (v *GetICPNeuronInfoReplyNeuronState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GetICPNeuronInfoReplyNeuronState(value)
	for _, existing := range AllowedGetICPNeuronInfoReplyNeuronStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GetICPNeuronInfoReplyNeuronState", value)
}

// NewGetICPNeuronInfoReplyNeuronStateFromValue returns a pointer to a valid GetICPNeuronInfoReplyNeuronState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGetICPNeuronInfoReplyNeuronStateFromValue(v string) (*GetICPNeuronInfoReplyNeuronState, error) {
	ev := GetICPNeuronInfoReplyNeuronState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GetICPNeuronInfoReplyNeuronState: valid values are %v", v, AllowedGetICPNeuronInfoReplyNeuronStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GetICPNeuronInfoReplyNeuronState) IsValid() bool {
	for _, existing := range AllowedGetICPNeuronInfoReplyNeuronStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GetICPNeuronInfoReplyNeuronState value
func (v GetICPNeuronInfoReplyNeuronState) Ptr() *GetICPNeuronInfoReplyNeuronState {
	return &v
}

type NullableGetICPNeuronInfoReplyNeuronState struct {
	value *GetICPNeuronInfoReplyNeuronState
	isSet bool
}

func (v NullableGetICPNeuronInfoReplyNeuronState) Get() *GetICPNeuronInfoReplyNeuronState {
	return v.value
}

func (v *NullableGetICPNeuronInfoReplyNeuronState) Set(val *GetICPNeuronInfoReplyNeuronState) {
	v.value = val
	v.isSet = true
}

func (v NullableGetICPNeuronInfoReplyNeuronState) IsSet() bool {
	return v.isSet
}

func (v *NullableGetICPNeuronInfoReplyNeuronState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetICPNeuronInfoReplyNeuronState(val *GetICPNeuronInfoReplyNeuronState) *NullableGetICPNeuronInfoReplyNeuronState {
	return &NullableGetICPNeuronInfoReplyNeuronState{value: val, isSet: true}
}

func (v NullableGetICPNeuronInfoReplyNeuronState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetICPNeuronInfoReplyNeuronState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

