/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TgvalidatordSignedWhitelistedAddressEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TgvalidatordSignedWhitelistedAddressEnvelope{}

// TgvalidatordSignedWhitelistedAddressEnvelope struct for TgvalidatordSignedWhitelistedAddressEnvelope
type TgvalidatordSignedWhitelistedAddressEnvelope struct {
	Id *string `json:"id,omitempty"`
	TenantId *string `json:"tenantId,omitempty"`
	SignedAddress *TgvalidatordSignedWhitelistedAddress `json:"signedAddress,omitempty"`
	Metadata *TgvalidatordMetadata `json:"metadata,omitempty"`
	Action *string `json:"action,omitempty"`
	Scores []TgvalidatordScore `json:"scores,omitempty"`
	Trails []TgvalidatordTrail `json:"trails,omitempty"`
	RulesContainer *string `json:"rulesContainer,omitempty"`
	Rule *string `json:"rule,omitempty"`
	Approvers *TgvalidatordApprovers `json:"approvers,omitempty"`
	Attributes []TgvalidatordWhitelistedAddressAttribute `json:"attributes,omitempty"`
	RulesContainerHash *string `json:"rulesContainerHash,omitempty"`
	Blockchain *string `json:"blockchain,omitempty"`
	Status *string `json:"status,omitempty"`
	Network *string `json:"network,omitempty"`
	VisibilityGroupID *string `json:"visibilityGroupID,omitempty"`
	TnParticipantID *string `json:"tnParticipantID,omitempty"`
	// (super-admin) Signature of rule container used for verification
	RulesSignatures *string `json:"rulesSignatures,omitempty"`
}

// NewTgvalidatordSignedWhitelistedAddressEnvelope instantiates a new TgvalidatordSignedWhitelistedAddressEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTgvalidatordSignedWhitelistedAddressEnvelope() *TgvalidatordSignedWhitelistedAddressEnvelope {
	this := TgvalidatordSignedWhitelistedAddressEnvelope{}
	return &this
}

// NewTgvalidatordSignedWhitelistedAddressEnvelopeWithDefaults instantiates a new TgvalidatordSignedWhitelistedAddressEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTgvalidatordSignedWhitelistedAddressEnvelopeWithDefaults() *TgvalidatordSignedWhitelistedAddressEnvelope {
	this := TgvalidatordSignedWhitelistedAddressEnvelope{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetId(v string) {
	o.Id = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetTenantId(v string) {
	o.TenantId = &v
}

// GetSignedAddress returns the SignedAddress field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetSignedAddress() TgvalidatordSignedWhitelistedAddress {
	if o == nil || IsNil(o.SignedAddress) {
		var ret TgvalidatordSignedWhitelistedAddress
		return ret
	}
	return *o.SignedAddress
}

// GetSignedAddressOk returns a tuple with the SignedAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetSignedAddressOk() (*TgvalidatordSignedWhitelistedAddress, bool) {
	if o == nil || IsNil(o.SignedAddress) {
		return nil, false
	}
	return o.SignedAddress, true
}

// HasSignedAddress returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasSignedAddress() bool {
	if o != nil && !IsNil(o.SignedAddress) {
		return true
	}

	return false
}

// SetSignedAddress gets a reference to the given TgvalidatordSignedWhitelistedAddress and assigns it to the SignedAddress field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetSignedAddress(v TgvalidatordSignedWhitelistedAddress) {
	o.SignedAddress = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetMetadata() TgvalidatordMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret TgvalidatordMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetMetadataOk() (*TgvalidatordMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given TgvalidatordMetadata and assigns it to the Metadata field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetMetadata(v TgvalidatordMetadata) {
	o.Metadata = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetAction(v string) {
	o.Action = &v
}

// GetScores returns the Scores field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetScores() []TgvalidatordScore {
	if o == nil || IsNil(o.Scores) {
		var ret []TgvalidatordScore
		return ret
	}
	return o.Scores
}

// GetScoresOk returns a tuple with the Scores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetScoresOk() ([]TgvalidatordScore, bool) {
	if o == nil || IsNil(o.Scores) {
		return nil, false
	}
	return o.Scores, true
}

// HasScores returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasScores() bool {
	if o != nil && !IsNil(o.Scores) {
		return true
	}

	return false
}

// SetScores gets a reference to the given []TgvalidatordScore and assigns it to the Scores field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetScores(v []TgvalidatordScore) {
	o.Scores = v
}

// GetTrails returns the Trails field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetTrails() []TgvalidatordTrail {
	if o == nil || IsNil(o.Trails) {
		var ret []TgvalidatordTrail
		return ret
	}
	return o.Trails
}

// GetTrailsOk returns a tuple with the Trails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetTrailsOk() ([]TgvalidatordTrail, bool) {
	if o == nil || IsNil(o.Trails) {
		return nil, false
	}
	return o.Trails, true
}

// HasTrails returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasTrails() bool {
	if o != nil && !IsNil(o.Trails) {
		return true
	}

	return false
}

// SetTrails gets a reference to the given []TgvalidatordTrail and assigns it to the Trails field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetTrails(v []TgvalidatordTrail) {
	o.Trails = v
}

// GetRulesContainer returns the RulesContainer field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetRulesContainer() string {
	if o == nil || IsNil(o.RulesContainer) {
		var ret string
		return ret
	}
	return *o.RulesContainer
}

// GetRulesContainerOk returns a tuple with the RulesContainer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetRulesContainerOk() (*string, bool) {
	if o == nil || IsNil(o.RulesContainer) {
		return nil, false
	}
	return o.RulesContainer, true
}

// HasRulesContainer returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasRulesContainer() bool {
	if o != nil && !IsNil(o.RulesContainer) {
		return true
	}

	return false
}

// SetRulesContainer gets a reference to the given string and assigns it to the RulesContainer field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetRulesContainer(v string) {
	o.RulesContainer = &v
}

// GetRule returns the Rule field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetRule() string {
	if o == nil || IsNil(o.Rule) {
		var ret string
		return ret
	}
	return *o.Rule
}

// GetRuleOk returns a tuple with the Rule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetRuleOk() (*string, bool) {
	if o == nil || IsNil(o.Rule) {
		return nil, false
	}
	return o.Rule, true
}

// HasRule returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasRule() bool {
	if o != nil && !IsNil(o.Rule) {
		return true
	}

	return false
}

// SetRule gets a reference to the given string and assigns it to the Rule field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetRule(v string) {
	o.Rule = &v
}

// GetApprovers returns the Approvers field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetApprovers() TgvalidatordApprovers {
	if o == nil || IsNil(o.Approvers) {
		var ret TgvalidatordApprovers
		return ret
	}
	return *o.Approvers
}

// GetApproversOk returns a tuple with the Approvers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetApproversOk() (*TgvalidatordApprovers, bool) {
	if o == nil || IsNil(o.Approvers) {
		return nil, false
	}
	return o.Approvers, true
}

// HasApprovers returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasApprovers() bool {
	if o != nil && !IsNil(o.Approvers) {
		return true
	}

	return false
}

// SetApprovers gets a reference to the given TgvalidatordApprovers and assigns it to the Approvers field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetApprovers(v TgvalidatordApprovers) {
	o.Approvers = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetAttributes() []TgvalidatordWhitelistedAddressAttribute {
	if o == nil || IsNil(o.Attributes) {
		var ret []TgvalidatordWhitelistedAddressAttribute
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetAttributesOk() ([]TgvalidatordWhitelistedAddressAttribute, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []TgvalidatordWhitelistedAddressAttribute and assigns it to the Attributes field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetAttributes(v []TgvalidatordWhitelistedAddressAttribute) {
	o.Attributes = v
}

// GetRulesContainerHash returns the RulesContainerHash field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetRulesContainerHash() string {
	if o == nil || IsNil(o.RulesContainerHash) {
		var ret string
		return ret
	}
	return *o.RulesContainerHash
}

// GetRulesContainerHashOk returns a tuple with the RulesContainerHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetRulesContainerHashOk() (*string, bool) {
	if o == nil || IsNil(o.RulesContainerHash) {
		return nil, false
	}
	return o.RulesContainerHash, true
}

// HasRulesContainerHash returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasRulesContainerHash() bool {
	if o != nil && !IsNil(o.RulesContainerHash) {
		return true
	}

	return false
}

// SetRulesContainerHash gets a reference to the given string and assigns it to the RulesContainerHash field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetRulesContainerHash(v string) {
	o.RulesContainerHash = &v
}

// GetBlockchain returns the Blockchain field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetBlockchain() string {
	if o == nil || IsNil(o.Blockchain) {
		var ret string
		return ret
	}
	return *o.Blockchain
}

// GetBlockchainOk returns a tuple with the Blockchain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetBlockchainOk() (*string, bool) {
	if o == nil || IsNil(o.Blockchain) {
		return nil, false
	}
	return o.Blockchain, true
}

// HasBlockchain returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasBlockchain() bool {
	if o != nil && !IsNil(o.Blockchain) {
		return true
	}

	return false
}

// SetBlockchain gets a reference to the given string and assigns it to the Blockchain field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetBlockchain(v string) {
	o.Blockchain = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetStatus(v string) {
	o.Status = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetNetwork(v string) {
	o.Network = &v
}

// GetVisibilityGroupID returns the VisibilityGroupID field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetVisibilityGroupID() string {
	if o == nil || IsNil(o.VisibilityGroupID) {
		var ret string
		return ret
	}
	return *o.VisibilityGroupID
}

// GetVisibilityGroupIDOk returns a tuple with the VisibilityGroupID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetVisibilityGroupIDOk() (*string, bool) {
	if o == nil || IsNil(o.VisibilityGroupID) {
		return nil, false
	}
	return o.VisibilityGroupID, true
}

// HasVisibilityGroupID returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasVisibilityGroupID() bool {
	if o != nil && !IsNil(o.VisibilityGroupID) {
		return true
	}

	return false
}

// SetVisibilityGroupID gets a reference to the given string and assigns it to the VisibilityGroupID field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetVisibilityGroupID(v string) {
	o.VisibilityGroupID = &v
}

// GetTnParticipantID returns the TnParticipantID field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetTnParticipantID() string {
	if o == nil || IsNil(o.TnParticipantID) {
		var ret string
		return ret
	}
	return *o.TnParticipantID
}

// GetTnParticipantIDOk returns a tuple with the TnParticipantID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetTnParticipantIDOk() (*string, bool) {
	if o == nil || IsNil(o.TnParticipantID) {
		return nil, false
	}
	return o.TnParticipantID, true
}

// HasTnParticipantID returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasTnParticipantID() bool {
	if o != nil && !IsNil(o.TnParticipantID) {
		return true
	}

	return false
}

// SetTnParticipantID gets a reference to the given string and assigns it to the TnParticipantID field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetTnParticipantID(v string) {
	o.TnParticipantID = &v
}

// GetRulesSignatures returns the RulesSignatures field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetRulesSignatures() string {
	if o == nil || IsNil(o.RulesSignatures) {
		var ret string
		return ret
	}
	return *o.RulesSignatures
}

// GetRulesSignaturesOk returns a tuple with the RulesSignatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) GetRulesSignaturesOk() (*string, bool) {
	if o == nil || IsNil(o.RulesSignatures) {
		return nil, false
	}
	return o.RulesSignatures, true
}

// HasRulesSignatures returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) HasRulesSignatures() bool {
	if o != nil && !IsNil(o.RulesSignatures) {
		return true
	}

	return false
}

// SetRulesSignatures gets a reference to the given string and assigns it to the RulesSignatures field.
func (o *TgvalidatordSignedWhitelistedAddressEnvelope) SetRulesSignatures(v string) {
	o.RulesSignatures = &v
}

func (o TgvalidatordSignedWhitelistedAddressEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TgvalidatordSignedWhitelistedAddressEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.SignedAddress) {
		toSerialize["signedAddress"] = o.SignedAddress
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Scores) {
		toSerialize["scores"] = o.Scores
	}
	if !IsNil(o.Trails) {
		toSerialize["trails"] = o.Trails
	}
	if !IsNil(o.RulesContainer) {
		toSerialize["rulesContainer"] = o.RulesContainer
	}
	if !IsNil(o.Rule) {
		toSerialize["rule"] = o.Rule
	}
	if !IsNil(o.Approvers) {
		toSerialize["approvers"] = o.Approvers
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.RulesContainerHash) {
		toSerialize["rulesContainerHash"] = o.RulesContainerHash
	}
	if !IsNil(o.Blockchain) {
		toSerialize["blockchain"] = o.Blockchain
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.VisibilityGroupID) {
		toSerialize["visibilityGroupID"] = o.VisibilityGroupID
	}
	if !IsNil(o.TnParticipantID) {
		toSerialize["tnParticipantID"] = o.TnParticipantID
	}
	if !IsNil(o.RulesSignatures) {
		toSerialize["rulesSignatures"] = o.RulesSignatures
	}
	return toSerialize, nil
}

type NullableTgvalidatordSignedWhitelistedAddressEnvelope struct {
	value *TgvalidatordSignedWhitelistedAddressEnvelope
	isSet bool
}

func (v NullableTgvalidatordSignedWhitelistedAddressEnvelope) Get() *TgvalidatordSignedWhitelistedAddressEnvelope {
	return v.value
}

func (v *NullableTgvalidatordSignedWhitelistedAddressEnvelope) Set(val *TgvalidatordSignedWhitelistedAddressEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableTgvalidatordSignedWhitelistedAddressEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableTgvalidatordSignedWhitelistedAddressEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTgvalidatordSignedWhitelistedAddressEnvelope(val *TgvalidatordSignedWhitelistedAddressEnvelope) *NullableTgvalidatordSignedWhitelistedAddressEnvelope {
	return &NullableTgvalidatordSignedWhitelistedAddressEnvelope{value: val, isSet: true}
}

func (v NullableTgvalidatordSignedWhitelistedAddressEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTgvalidatordSignedWhitelistedAddressEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


