/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest{}

// TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest struct for TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest
type TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// NewTgvalidatordUpdateTransactionsEnabledBusinessRuleRequest instantiates a new TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTgvalidatordUpdateTransactionsEnabledBusinessRuleRequest() *TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest {
	this := TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest{}
	return &this
}

// NewTgvalidatordUpdateTransactionsEnabledBusinessRuleRequestWithDefaults instantiates a new TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTgvalidatordUpdateTransactionsEnabledBusinessRuleRequestWithDefaults() *TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest {
	this := TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableTgvalidatordUpdateTransactionsEnabledBusinessRuleRequest struct {
	value *TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest
	isSet bool
}

func (v NullableTgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) Get() *TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest {
	return v.value
}

func (v *NullableTgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) Set(val *TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTgvalidatordUpdateTransactionsEnabledBusinessRuleRequest(val *TgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) *NullableTgvalidatordUpdateTransactionsEnabledBusinessRuleRequest {
	return &NullableTgvalidatordUpdateTransactionsEnabledBusinessRuleRequest{value: val, isSet: true}
}

func (v NullableTgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTgvalidatordUpdateTransactionsEnabledBusinessRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


