/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TgvalidatordSignedWhitelistedContractAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TgvalidatordSignedWhitelistedContractAddress{}

// TgvalidatordSignedWhitelistedContractAddress struct for TgvalidatordSignedWhitelistedContractAddress
type TgvalidatordSignedWhitelistedContractAddress struct {
	Signatures []TgvalidatordWhitelistSignature `json:"signatures,omitempty"`
	Payload *string `json:"payload,omitempty" validate:"regexp=^(?:[A-Za-z0-9+\\/]{4})*(?:[A-Za-z0-9+\\/]{2}==|[A-Za-z0-9+\\/]{3}=)?$"`
}

// NewTgvalidatordSignedWhitelistedContractAddress instantiates a new TgvalidatordSignedWhitelistedContractAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTgvalidatordSignedWhitelistedContractAddress() *TgvalidatordSignedWhitelistedContractAddress {
	this := TgvalidatordSignedWhitelistedContractAddress{}
	return &this
}

// NewTgvalidatordSignedWhitelistedContractAddressWithDefaults instantiates a new TgvalidatordSignedWhitelistedContractAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTgvalidatordSignedWhitelistedContractAddressWithDefaults() *TgvalidatordSignedWhitelistedContractAddress {
	this := TgvalidatordSignedWhitelistedContractAddress{}
	return &this
}

// GetSignatures returns the Signatures field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedContractAddress) GetSignatures() []TgvalidatordWhitelistSignature {
	if o == nil || IsNil(o.Signatures) {
		var ret []TgvalidatordWhitelistSignature
		return ret
	}
	return o.Signatures
}

// GetSignaturesOk returns a tuple with the Signatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedContractAddress) GetSignaturesOk() ([]TgvalidatordWhitelistSignature, bool) {
	if o == nil || IsNil(o.Signatures) {
		return nil, false
	}
	return o.Signatures, true
}

// HasSignatures returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedContractAddress) HasSignatures() bool {
	if o != nil && !IsNil(o.Signatures) {
		return true
	}

	return false
}

// SetSignatures gets a reference to the given []TgvalidatordWhitelistSignature and assigns it to the Signatures field.
func (o *TgvalidatordSignedWhitelistedContractAddress) SetSignatures(v []TgvalidatordWhitelistSignature) {
	o.Signatures = v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *TgvalidatordSignedWhitelistedContractAddress) GetPayload() string {
	if o == nil || IsNil(o.Payload) {
		var ret string
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordSignedWhitelistedContractAddress) GetPayloadOk() (*string, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *TgvalidatordSignedWhitelistedContractAddress) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given string and assigns it to the Payload field.
func (o *TgvalidatordSignedWhitelistedContractAddress) SetPayload(v string) {
	o.Payload = &v
}

func (o TgvalidatordSignedWhitelistedContractAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TgvalidatordSignedWhitelistedContractAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Signatures) {
		toSerialize["signatures"] = o.Signatures
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	return toSerialize, nil
}

type NullableTgvalidatordSignedWhitelistedContractAddress struct {
	value *TgvalidatordSignedWhitelistedContractAddress
	isSet bool
}

func (v NullableTgvalidatordSignedWhitelistedContractAddress) Get() *TgvalidatordSignedWhitelistedContractAddress {
	return v.value
}

func (v *NullableTgvalidatordSignedWhitelistedContractAddress) Set(val *TgvalidatordSignedWhitelistedContractAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableTgvalidatordSignedWhitelistedContractAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableTgvalidatordSignedWhitelistedContractAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTgvalidatordSignedWhitelistedContractAddress(val *TgvalidatordSignedWhitelistedContractAddress) *NullableTgvalidatordSignedWhitelistedContractAddress {
	return &NullableTgvalidatordSignedWhitelistedContractAddress{value: val, isSet: true}
}

func (v NullableTgvalidatordSignedWhitelistedContractAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTgvalidatordSignedWhitelistedContractAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


