/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TgvalidatordBurnOperationDetailsV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TgvalidatordBurnOperationDetailsV2{}

// TgvalidatordBurnOperationDetailsV2 struct for TgvalidatordBurnOperationDetailsV2
type TgvalidatordBurnOperationDetailsV2 struct {
	Destination *TgvalidatordAddressTargetV2 `json:"destination,omitempty"`
	Amount *string `json:"amount,omitempty"`
	NftTokenIDs []string `json:"nftTokenIDs,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TgvalidatordBurnOperationDetailsV2 TgvalidatordBurnOperationDetailsV2

// NewTgvalidatordBurnOperationDetailsV2 instantiates a new TgvalidatordBurnOperationDetailsV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTgvalidatordBurnOperationDetailsV2() *TgvalidatordBurnOperationDetailsV2 {
	this := TgvalidatordBurnOperationDetailsV2{}
	return &this
}

// NewTgvalidatordBurnOperationDetailsV2WithDefaults instantiates a new TgvalidatordBurnOperationDetailsV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTgvalidatordBurnOperationDetailsV2WithDefaults() *TgvalidatordBurnOperationDetailsV2 {
	this := TgvalidatordBurnOperationDetailsV2{}
	return &this
}

// GetDestination returns the Destination field value if set, zero value otherwise.
func (o *TgvalidatordBurnOperationDetailsV2) GetDestination() TgvalidatordAddressTargetV2 {
	if o == nil || IsNil(o.Destination) {
		var ret TgvalidatordAddressTargetV2
		return ret
	}
	return *o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordBurnOperationDetailsV2) GetDestinationOk() (*TgvalidatordAddressTargetV2, bool) {
	if o == nil || IsNil(o.Destination) {
		return nil, false
	}
	return o.Destination, true
}

// HasDestination returns a boolean if a field has been set.
func (o *TgvalidatordBurnOperationDetailsV2) HasDestination() bool {
	if o != nil && !IsNil(o.Destination) {
		return true
	}

	return false
}

// SetDestination gets a reference to the given TgvalidatordAddressTargetV2 and assigns it to the Destination field.
func (o *TgvalidatordBurnOperationDetailsV2) SetDestination(v TgvalidatordAddressTargetV2) {
	o.Destination = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *TgvalidatordBurnOperationDetailsV2) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordBurnOperationDetailsV2) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *TgvalidatordBurnOperationDetailsV2) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *TgvalidatordBurnOperationDetailsV2) SetAmount(v string) {
	o.Amount = &v
}

// GetNftTokenIDs returns the NftTokenIDs field value if set, zero value otherwise.
func (o *TgvalidatordBurnOperationDetailsV2) GetNftTokenIDs() []string {
	if o == nil || IsNil(o.NftTokenIDs) {
		var ret []string
		return ret
	}
	return o.NftTokenIDs
}

// GetNftTokenIDsOk returns a tuple with the NftTokenIDs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordBurnOperationDetailsV2) GetNftTokenIDsOk() ([]string, bool) {
	if o == nil || IsNil(o.NftTokenIDs) {
		return nil, false
	}
	return o.NftTokenIDs, true
}

// HasNftTokenIDs returns a boolean if a field has been set.
func (o *TgvalidatordBurnOperationDetailsV2) HasNftTokenIDs() bool {
	if o != nil && !IsNil(o.NftTokenIDs) {
		return true
	}

	return false
}

// SetNftTokenIDs gets a reference to the given []string and assigns it to the NftTokenIDs field.
func (o *TgvalidatordBurnOperationDetailsV2) SetNftTokenIDs(v []string) {
	o.NftTokenIDs = v
}

func (o TgvalidatordBurnOperationDetailsV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TgvalidatordBurnOperationDetailsV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Destination) {
		toSerialize["destination"] = o.Destination
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.NftTokenIDs) {
		toSerialize["nftTokenIDs"] = o.NftTokenIDs
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TgvalidatordBurnOperationDetailsV2) UnmarshalJSON(data []byte) (err error) {
	varTgvalidatordBurnOperationDetailsV2 := _TgvalidatordBurnOperationDetailsV2{}

	err = json.Unmarshal(data, &varTgvalidatordBurnOperationDetailsV2)

	if err != nil {
		return err
	}

	*o = TgvalidatordBurnOperationDetailsV2(varTgvalidatordBurnOperationDetailsV2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "destination")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "nftTokenIDs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTgvalidatordBurnOperationDetailsV2 struct {
	value *TgvalidatordBurnOperationDetailsV2
	isSet bool
}

func (v NullableTgvalidatordBurnOperationDetailsV2) Get() *TgvalidatordBurnOperationDetailsV2 {
	return v.value
}

func (v *NullableTgvalidatordBurnOperationDetailsV2) Set(val *TgvalidatordBurnOperationDetailsV2) {
	v.value = val
	v.isSet = true
}

func (v NullableTgvalidatordBurnOperationDetailsV2) IsSet() bool {
	return v.isSet
}

func (v *NullableTgvalidatordBurnOperationDetailsV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTgvalidatordBurnOperationDetailsV2(val *TgvalidatordBurnOperationDetailsV2) *NullableTgvalidatordBurnOperationDetailsV2 {
	return &NullableTgvalidatordBurnOperationDetailsV2{value: val, isSet: true}
}

func (v NullableTgvalidatordBurnOperationDetailsV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTgvalidatordBurnOperationDetailsV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


