/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TgvalidatordGetChangesReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TgvalidatordGetChangesReply{}

// TgvalidatordGetChangesReply struct for TgvalidatordGetChangesReply
type TgvalidatordGetChangesReply struct {
	Result []TgvalidatordChange `json:"result,omitempty"`
	Cursor *TgvalidatordResponseCursor `json:"cursor,omitempty"`
}

// NewTgvalidatordGetChangesReply instantiates a new TgvalidatordGetChangesReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTgvalidatordGetChangesReply() *TgvalidatordGetChangesReply {
	this := TgvalidatordGetChangesReply{}
	return &this
}

// NewTgvalidatordGetChangesReplyWithDefaults instantiates a new TgvalidatordGetChangesReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTgvalidatordGetChangesReplyWithDefaults() *TgvalidatordGetChangesReply {
	this := TgvalidatordGetChangesReply{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *TgvalidatordGetChangesReply) GetResult() []TgvalidatordChange {
	if o == nil || IsNil(o.Result) {
		var ret []TgvalidatordChange
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordGetChangesReply) GetResultOk() ([]TgvalidatordChange, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *TgvalidatordGetChangesReply) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given []TgvalidatordChange and assigns it to the Result field.
func (o *TgvalidatordGetChangesReply) SetResult(v []TgvalidatordChange) {
	o.Result = v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *TgvalidatordGetChangesReply) GetCursor() TgvalidatordResponseCursor {
	if o == nil || IsNil(o.Cursor) {
		var ret TgvalidatordResponseCursor
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordGetChangesReply) GetCursorOk() (*TgvalidatordResponseCursor, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *TgvalidatordGetChangesReply) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given TgvalidatordResponseCursor and assigns it to the Cursor field.
func (o *TgvalidatordGetChangesReply) SetCursor(v TgvalidatordResponseCursor) {
	o.Cursor = &v
}

func (o TgvalidatordGetChangesReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TgvalidatordGetChangesReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	return toSerialize, nil
}

type NullableTgvalidatordGetChangesReply struct {
	value *TgvalidatordGetChangesReply
	isSet bool
}

func (v NullableTgvalidatordGetChangesReply) Get() *TgvalidatordGetChangesReply {
	return v.value
}

func (v *NullableTgvalidatordGetChangesReply) Set(val *TgvalidatordGetChangesReply) {
	v.value = val
	v.isSet = true
}

func (v NullableTgvalidatordGetChangesReply) IsSet() bool {
	return v.isSet
}

func (v *NullableTgvalidatordGetChangesReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTgvalidatordGetChangesReply(val *TgvalidatordGetChangesReply) *NullableTgvalidatordGetChangesReply {
	return &NullableTgvalidatordGetChangesReply{value: val, isSet: true}
}

func (v NullableTgvalidatordGetChangesReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTgvalidatordGetChangesReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


