/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TgvalidatordScimUserList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TgvalidatordScimUserList{}

// TgvalidatordScimUserList struct for TgvalidatordScimUserList
type TgvalidatordScimUserList struct {
	Schemas []string `json:"schemas,omitempty"`
	TotalResults *int64 `json:"totalResults,omitempty"`
	Resources []TgvalidatordScimUser `json:"Resources,omitempty"`
	ItemsPerPage *int64 `json:"itemsPerPage,omitempty"`
	StartIndex *int64 `json:"startIndex,omitempty"`
}

// NewTgvalidatordScimUserList instantiates a new TgvalidatordScimUserList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTgvalidatordScimUserList() *TgvalidatordScimUserList {
	this := TgvalidatordScimUserList{}
	return &this
}

// NewTgvalidatordScimUserListWithDefaults instantiates a new TgvalidatordScimUserList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTgvalidatordScimUserListWithDefaults() *TgvalidatordScimUserList {
	this := TgvalidatordScimUserList{}
	return &this
}

// GetSchemas returns the Schemas field value if set, zero value otherwise.
func (o *TgvalidatordScimUserList) GetSchemas() []string {
	if o == nil || IsNil(o.Schemas) {
		var ret []string
		return ret
	}
	return o.Schemas
}

// GetSchemasOk returns a tuple with the Schemas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordScimUserList) GetSchemasOk() ([]string, bool) {
	if o == nil || IsNil(o.Schemas) {
		return nil, false
	}
	return o.Schemas, true
}

// HasSchemas returns a boolean if a field has been set.
func (o *TgvalidatordScimUserList) HasSchemas() bool {
	if o != nil && !IsNil(o.Schemas) {
		return true
	}

	return false
}

// SetSchemas gets a reference to the given []string and assigns it to the Schemas field.
func (o *TgvalidatordScimUserList) SetSchemas(v []string) {
	o.Schemas = v
}

// GetTotalResults returns the TotalResults field value if set, zero value otherwise.
func (o *TgvalidatordScimUserList) GetTotalResults() int64 {
	if o == nil || IsNil(o.TotalResults) {
		var ret int64
		return ret
	}
	return *o.TotalResults
}

// GetTotalResultsOk returns a tuple with the TotalResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordScimUserList) GetTotalResultsOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalResults) {
		return nil, false
	}
	return o.TotalResults, true
}

// HasTotalResults returns a boolean if a field has been set.
func (o *TgvalidatordScimUserList) HasTotalResults() bool {
	if o != nil && !IsNil(o.TotalResults) {
		return true
	}

	return false
}

// SetTotalResults gets a reference to the given int64 and assigns it to the TotalResults field.
func (o *TgvalidatordScimUserList) SetTotalResults(v int64) {
	o.TotalResults = &v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *TgvalidatordScimUserList) GetResources() []TgvalidatordScimUser {
	if o == nil || IsNil(o.Resources) {
		var ret []TgvalidatordScimUser
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordScimUserList) GetResourcesOk() ([]TgvalidatordScimUser, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *TgvalidatordScimUserList) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given []TgvalidatordScimUser and assigns it to the Resources field.
func (o *TgvalidatordScimUserList) SetResources(v []TgvalidatordScimUser) {
	o.Resources = v
}

// GetItemsPerPage returns the ItemsPerPage field value if set, zero value otherwise.
func (o *TgvalidatordScimUserList) GetItemsPerPage() int64 {
	if o == nil || IsNil(o.ItemsPerPage) {
		var ret int64
		return ret
	}
	return *o.ItemsPerPage
}

// GetItemsPerPageOk returns a tuple with the ItemsPerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordScimUserList) GetItemsPerPageOk() (*int64, bool) {
	if o == nil || IsNil(o.ItemsPerPage) {
		return nil, false
	}
	return o.ItemsPerPage, true
}

// HasItemsPerPage returns a boolean if a field has been set.
func (o *TgvalidatordScimUserList) HasItemsPerPage() bool {
	if o != nil && !IsNil(o.ItemsPerPage) {
		return true
	}

	return false
}

// SetItemsPerPage gets a reference to the given int64 and assigns it to the ItemsPerPage field.
func (o *TgvalidatordScimUserList) SetItemsPerPage(v int64) {
	o.ItemsPerPage = &v
}

// GetStartIndex returns the StartIndex field value if set, zero value otherwise.
func (o *TgvalidatordScimUserList) GetStartIndex() int64 {
	if o == nil || IsNil(o.StartIndex) {
		var ret int64
		return ret
	}
	return *o.StartIndex
}

// GetStartIndexOk returns a tuple with the StartIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordScimUserList) GetStartIndexOk() (*int64, bool) {
	if o == nil || IsNil(o.StartIndex) {
		return nil, false
	}
	return o.StartIndex, true
}

// HasStartIndex returns a boolean if a field has been set.
func (o *TgvalidatordScimUserList) HasStartIndex() bool {
	if o != nil && !IsNil(o.StartIndex) {
		return true
	}

	return false
}

// SetStartIndex gets a reference to the given int64 and assigns it to the StartIndex field.
func (o *TgvalidatordScimUserList) SetStartIndex(v int64) {
	o.StartIndex = &v
}

func (o TgvalidatordScimUserList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TgvalidatordScimUserList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schemas) {
		toSerialize["schemas"] = o.Schemas
	}
	if !IsNil(o.TotalResults) {
		toSerialize["totalResults"] = o.TotalResults
	}
	if !IsNil(o.Resources) {
		toSerialize["Resources"] = o.Resources
	}
	if !IsNil(o.ItemsPerPage) {
		toSerialize["itemsPerPage"] = o.ItemsPerPage
	}
	if !IsNil(o.StartIndex) {
		toSerialize["startIndex"] = o.StartIndex
	}
	return toSerialize, nil
}

type NullableTgvalidatordScimUserList struct {
	value *TgvalidatordScimUserList
	isSet bool
}

func (v NullableTgvalidatordScimUserList) Get() *TgvalidatordScimUserList {
	return v.value
}

func (v *NullableTgvalidatordScimUserList) Set(val *TgvalidatordScimUserList) {
	v.value = val
	v.isSet = true
}

func (v NullableTgvalidatordScimUserList) IsSet() bool {
	return v.isSet
}

func (v *NullableTgvalidatordScimUserList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTgvalidatordScimUserList(val *TgvalidatordScimUserList) *NullableTgvalidatordScimUserList {
	return &NullableTgvalidatordScimUserList{value: val, isSet: true}
}

func (v NullableTgvalidatordScimUserList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTgvalidatordScimUserList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


