/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TgvalidatordInternalGroupUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TgvalidatordInternalGroupUser{}

// TgvalidatordInternalGroupUser struct for TgvalidatordInternalGroupUser
type TgvalidatordInternalGroupUser struct {
	Id *string `json:"id,omitempty"`
	ExternalUserId *string `json:"externalUserId,omitempty"`
	EnforcedInRules *bool `json:"enforcedInRules,omitempty"`
}

// NewTgvalidatordInternalGroupUser instantiates a new TgvalidatordInternalGroupUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTgvalidatordInternalGroupUser() *TgvalidatordInternalGroupUser {
	this := TgvalidatordInternalGroupUser{}
	return &this
}

// NewTgvalidatordInternalGroupUserWithDefaults instantiates a new TgvalidatordInternalGroupUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTgvalidatordInternalGroupUserWithDefaults() *TgvalidatordInternalGroupUser {
	this := TgvalidatordInternalGroupUser{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TgvalidatordInternalGroupUser) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordInternalGroupUser) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TgvalidatordInternalGroupUser) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TgvalidatordInternalGroupUser) SetId(v string) {
	o.Id = &v
}

// GetExternalUserId returns the ExternalUserId field value if set, zero value otherwise.
func (o *TgvalidatordInternalGroupUser) GetExternalUserId() string {
	if o == nil || IsNil(o.ExternalUserId) {
		var ret string
		return ret
	}
	return *o.ExternalUserId
}

// GetExternalUserIdOk returns a tuple with the ExternalUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordInternalGroupUser) GetExternalUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalUserId) {
		return nil, false
	}
	return o.ExternalUserId, true
}

// HasExternalUserId returns a boolean if a field has been set.
func (o *TgvalidatordInternalGroupUser) HasExternalUserId() bool {
	if o != nil && !IsNil(o.ExternalUserId) {
		return true
	}

	return false
}

// SetExternalUserId gets a reference to the given string and assigns it to the ExternalUserId field.
func (o *TgvalidatordInternalGroupUser) SetExternalUserId(v string) {
	o.ExternalUserId = &v
}

// GetEnforcedInRules returns the EnforcedInRules field value if set, zero value otherwise.
func (o *TgvalidatordInternalGroupUser) GetEnforcedInRules() bool {
	if o == nil || IsNil(o.EnforcedInRules) {
		var ret bool
		return ret
	}
	return *o.EnforcedInRules
}

// GetEnforcedInRulesOk returns a tuple with the EnforcedInRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordInternalGroupUser) GetEnforcedInRulesOk() (*bool, bool) {
	if o == nil || IsNil(o.EnforcedInRules) {
		return nil, false
	}
	return o.EnforcedInRules, true
}

// HasEnforcedInRules returns a boolean if a field has been set.
func (o *TgvalidatordInternalGroupUser) HasEnforcedInRules() bool {
	if o != nil && !IsNil(o.EnforcedInRules) {
		return true
	}

	return false
}

// SetEnforcedInRules gets a reference to the given bool and assigns it to the EnforcedInRules field.
func (o *TgvalidatordInternalGroupUser) SetEnforcedInRules(v bool) {
	o.EnforcedInRules = &v
}

func (o TgvalidatordInternalGroupUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TgvalidatordInternalGroupUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ExternalUserId) {
		toSerialize["externalUserId"] = o.ExternalUserId
	}
	if !IsNil(o.EnforcedInRules) {
		toSerialize["enforcedInRules"] = o.EnforcedInRules
	}
	return toSerialize, nil
}

type NullableTgvalidatordInternalGroupUser struct {
	value *TgvalidatordInternalGroupUser
	isSet bool
}

func (v NullableTgvalidatordInternalGroupUser) Get() *TgvalidatordInternalGroupUser {
	return v.value
}

func (v *NullableTgvalidatordInternalGroupUser) Set(val *TgvalidatordInternalGroupUser) {
	v.value = val
	v.isSet = true
}

func (v NullableTgvalidatordInternalGroupUser) IsSet() bool {
	return v.isSet
}

func (v *NullableTgvalidatordInternalGroupUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTgvalidatordInternalGroupUser(val *TgvalidatordInternalGroupUser) *NullableTgvalidatordInternalGroupUser {
	return &NullableTgvalidatordInternalGroupUser{value: val, isSet: true}
}

func (v NullableTgvalidatordInternalGroupUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTgvalidatordInternalGroupUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


