/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the TgvalidatordTnPledge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TgvalidatordTnPledge{}

// TgvalidatordTnPledge struct for TgvalidatordTnPledge
type TgvalidatordTnPledge struct {
	Id *string `json:"id,omitempty"`
	SharedAddressID *string `json:"sharedAddressID,omitempty"`
	OwnerParticipantID *string `json:"ownerParticipantID,omitempty"`
	TargetParticipantID *string `json:"targetParticipantID,omitempty"`
	CurrencyID *string `json:"currencyID,omitempty"`
	Blockchain *string `json:"blockchain,omitempty"`
	Network *string `json:"network,omitempty"`
	Arg1 *string `json:"arg1,omitempty"`
	Arg2 *string `json:"arg2,omitempty"`
	Amount *string `json:"amount,omitempty"`
	Status *string `json:"status,omitempty"`
	PledgeType *string `json:"pledgeType,omitempty"`
	Trails []TgvalidatordTnPledgeTrail `json:"trails,omitempty"`
	OriginCreationDate *time.Time `json:"originCreationDate,omitempty"`
	DurationSetup *TnPledgePledgeDurationSetup `json:"durationSetup,omitempty"`
	UnpledgeDate *time.Time `json:"unpledgeDate,omitempty"`
	Attributes []TnPledgePledgeAttribute `json:"attributes,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	ExternalReferenceId *string `json:"externalReferenceId,omitempty"`
	ReconciliationNote *string `json:"reconciliationNote,omitempty"`
	Direction *string `json:"direction,omitempty"`
	// Represent the id of a whitelisted address if your participant is the target participant of the pledge. internalAddressID and wladdressID can not be set simultaneously.
	WladdressID *string `json:"wladdressID,omitempty"`
}

// NewTgvalidatordTnPledge instantiates a new TgvalidatordTnPledge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTgvalidatordTnPledge() *TgvalidatordTnPledge {
	this := TgvalidatordTnPledge{}
	return &this
}

// NewTgvalidatordTnPledgeWithDefaults instantiates a new TgvalidatordTnPledge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTgvalidatordTnPledgeWithDefaults() *TgvalidatordTnPledge {
	this := TgvalidatordTnPledge{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TgvalidatordTnPledge) SetId(v string) {
	o.Id = &v
}

// GetSharedAddressID returns the SharedAddressID field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetSharedAddressID() string {
	if o == nil || IsNil(o.SharedAddressID) {
		var ret string
		return ret
	}
	return *o.SharedAddressID
}

// GetSharedAddressIDOk returns a tuple with the SharedAddressID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetSharedAddressIDOk() (*string, bool) {
	if o == nil || IsNil(o.SharedAddressID) {
		return nil, false
	}
	return o.SharedAddressID, true
}

// HasSharedAddressID returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasSharedAddressID() bool {
	if o != nil && !IsNil(o.SharedAddressID) {
		return true
	}

	return false
}

// SetSharedAddressID gets a reference to the given string and assigns it to the SharedAddressID field.
func (o *TgvalidatordTnPledge) SetSharedAddressID(v string) {
	o.SharedAddressID = &v
}

// GetOwnerParticipantID returns the OwnerParticipantID field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetOwnerParticipantID() string {
	if o == nil || IsNil(o.OwnerParticipantID) {
		var ret string
		return ret
	}
	return *o.OwnerParticipantID
}

// GetOwnerParticipantIDOk returns a tuple with the OwnerParticipantID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetOwnerParticipantIDOk() (*string, bool) {
	if o == nil || IsNil(o.OwnerParticipantID) {
		return nil, false
	}
	return o.OwnerParticipantID, true
}

// HasOwnerParticipantID returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasOwnerParticipantID() bool {
	if o != nil && !IsNil(o.OwnerParticipantID) {
		return true
	}

	return false
}

// SetOwnerParticipantID gets a reference to the given string and assigns it to the OwnerParticipantID field.
func (o *TgvalidatordTnPledge) SetOwnerParticipantID(v string) {
	o.OwnerParticipantID = &v
}

// GetTargetParticipantID returns the TargetParticipantID field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetTargetParticipantID() string {
	if o == nil || IsNil(o.TargetParticipantID) {
		var ret string
		return ret
	}
	return *o.TargetParticipantID
}

// GetTargetParticipantIDOk returns a tuple with the TargetParticipantID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetTargetParticipantIDOk() (*string, bool) {
	if o == nil || IsNil(o.TargetParticipantID) {
		return nil, false
	}
	return o.TargetParticipantID, true
}

// HasTargetParticipantID returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasTargetParticipantID() bool {
	if o != nil && !IsNil(o.TargetParticipantID) {
		return true
	}

	return false
}

// SetTargetParticipantID gets a reference to the given string and assigns it to the TargetParticipantID field.
func (o *TgvalidatordTnPledge) SetTargetParticipantID(v string) {
	o.TargetParticipantID = &v
}

// GetCurrencyID returns the CurrencyID field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetCurrencyID() string {
	if o == nil || IsNil(o.CurrencyID) {
		var ret string
		return ret
	}
	return *o.CurrencyID
}

// GetCurrencyIDOk returns a tuple with the CurrencyID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetCurrencyIDOk() (*string, bool) {
	if o == nil || IsNil(o.CurrencyID) {
		return nil, false
	}
	return o.CurrencyID, true
}

// HasCurrencyID returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasCurrencyID() bool {
	if o != nil && !IsNil(o.CurrencyID) {
		return true
	}

	return false
}

// SetCurrencyID gets a reference to the given string and assigns it to the CurrencyID field.
func (o *TgvalidatordTnPledge) SetCurrencyID(v string) {
	o.CurrencyID = &v
}

// GetBlockchain returns the Blockchain field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetBlockchain() string {
	if o == nil || IsNil(o.Blockchain) {
		var ret string
		return ret
	}
	return *o.Blockchain
}

// GetBlockchainOk returns a tuple with the Blockchain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetBlockchainOk() (*string, bool) {
	if o == nil || IsNil(o.Blockchain) {
		return nil, false
	}
	return o.Blockchain, true
}

// HasBlockchain returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasBlockchain() bool {
	if o != nil && !IsNil(o.Blockchain) {
		return true
	}

	return false
}

// SetBlockchain gets a reference to the given string and assigns it to the Blockchain field.
func (o *TgvalidatordTnPledge) SetBlockchain(v string) {
	o.Blockchain = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *TgvalidatordTnPledge) SetNetwork(v string) {
	o.Network = &v
}

// GetArg1 returns the Arg1 field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetArg1() string {
	if o == nil || IsNil(o.Arg1) {
		var ret string
		return ret
	}
	return *o.Arg1
}

// GetArg1Ok returns a tuple with the Arg1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetArg1Ok() (*string, bool) {
	if o == nil || IsNil(o.Arg1) {
		return nil, false
	}
	return o.Arg1, true
}

// HasArg1 returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasArg1() bool {
	if o != nil && !IsNil(o.Arg1) {
		return true
	}

	return false
}

// SetArg1 gets a reference to the given string and assigns it to the Arg1 field.
func (o *TgvalidatordTnPledge) SetArg1(v string) {
	o.Arg1 = &v
}

// GetArg2 returns the Arg2 field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetArg2() string {
	if o == nil || IsNil(o.Arg2) {
		var ret string
		return ret
	}
	return *o.Arg2
}

// GetArg2Ok returns a tuple with the Arg2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetArg2Ok() (*string, bool) {
	if o == nil || IsNil(o.Arg2) {
		return nil, false
	}
	return o.Arg2, true
}

// HasArg2 returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasArg2() bool {
	if o != nil && !IsNil(o.Arg2) {
		return true
	}

	return false
}

// SetArg2 gets a reference to the given string and assigns it to the Arg2 field.
func (o *TgvalidatordTnPledge) SetArg2(v string) {
	o.Arg2 = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *TgvalidatordTnPledge) SetAmount(v string) {
	o.Amount = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TgvalidatordTnPledge) SetStatus(v string) {
	o.Status = &v
}

// GetPledgeType returns the PledgeType field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetPledgeType() string {
	if o == nil || IsNil(o.PledgeType) {
		var ret string
		return ret
	}
	return *o.PledgeType
}

// GetPledgeTypeOk returns a tuple with the PledgeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetPledgeTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PledgeType) {
		return nil, false
	}
	return o.PledgeType, true
}

// HasPledgeType returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasPledgeType() bool {
	if o != nil && !IsNil(o.PledgeType) {
		return true
	}

	return false
}

// SetPledgeType gets a reference to the given string and assigns it to the PledgeType field.
func (o *TgvalidatordTnPledge) SetPledgeType(v string) {
	o.PledgeType = &v
}

// GetTrails returns the Trails field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetTrails() []TgvalidatordTnPledgeTrail {
	if o == nil || IsNil(o.Trails) {
		var ret []TgvalidatordTnPledgeTrail
		return ret
	}
	return o.Trails
}

// GetTrailsOk returns a tuple with the Trails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetTrailsOk() ([]TgvalidatordTnPledgeTrail, bool) {
	if o == nil || IsNil(o.Trails) {
		return nil, false
	}
	return o.Trails, true
}

// HasTrails returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasTrails() bool {
	if o != nil && !IsNil(o.Trails) {
		return true
	}

	return false
}

// SetTrails gets a reference to the given []TgvalidatordTnPledgeTrail and assigns it to the Trails field.
func (o *TgvalidatordTnPledge) SetTrails(v []TgvalidatordTnPledgeTrail) {
	o.Trails = v
}

// GetOriginCreationDate returns the OriginCreationDate field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetOriginCreationDate() time.Time {
	if o == nil || IsNil(o.OriginCreationDate) {
		var ret time.Time
		return ret
	}
	return *o.OriginCreationDate
}

// GetOriginCreationDateOk returns a tuple with the OriginCreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetOriginCreationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.OriginCreationDate) {
		return nil, false
	}
	return o.OriginCreationDate, true
}

// HasOriginCreationDate returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasOriginCreationDate() bool {
	if o != nil && !IsNil(o.OriginCreationDate) {
		return true
	}

	return false
}

// SetOriginCreationDate gets a reference to the given time.Time and assigns it to the OriginCreationDate field.
func (o *TgvalidatordTnPledge) SetOriginCreationDate(v time.Time) {
	o.OriginCreationDate = &v
}

// GetDurationSetup returns the DurationSetup field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetDurationSetup() TnPledgePledgeDurationSetup {
	if o == nil || IsNil(o.DurationSetup) {
		var ret TnPledgePledgeDurationSetup
		return ret
	}
	return *o.DurationSetup
}

// GetDurationSetupOk returns a tuple with the DurationSetup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetDurationSetupOk() (*TnPledgePledgeDurationSetup, bool) {
	if o == nil || IsNil(o.DurationSetup) {
		return nil, false
	}
	return o.DurationSetup, true
}

// HasDurationSetup returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasDurationSetup() bool {
	if o != nil && !IsNil(o.DurationSetup) {
		return true
	}

	return false
}

// SetDurationSetup gets a reference to the given TnPledgePledgeDurationSetup and assigns it to the DurationSetup field.
func (o *TgvalidatordTnPledge) SetDurationSetup(v TnPledgePledgeDurationSetup) {
	o.DurationSetup = &v
}

// GetUnpledgeDate returns the UnpledgeDate field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetUnpledgeDate() time.Time {
	if o == nil || IsNil(o.UnpledgeDate) {
		var ret time.Time
		return ret
	}
	return *o.UnpledgeDate
}

// GetUnpledgeDateOk returns a tuple with the UnpledgeDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetUnpledgeDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UnpledgeDate) {
		return nil, false
	}
	return o.UnpledgeDate, true
}

// HasUnpledgeDate returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasUnpledgeDate() bool {
	if o != nil && !IsNil(o.UnpledgeDate) {
		return true
	}

	return false
}

// SetUnpledgeDate gets a reference to the given time.Time and assigns it to the UnpledgeDate field.
func (o *TgvalidatordTnPledge) SetUnpledgeDate(v time.Time) {
	o.UnpledgeDate = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetAttributes() []TnPledgePledgeAttribute {
	if o == nil || IsNil(o.Attributes) {
		var ret []TnPledgePledgeAttribute
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetAttributesOk() ([]TnPledgePledgeAttribute, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []TnPledgePledgeAttribute and assigns it to the Attributes field.
func (o *TgvalidatordTnPledge) SetAttributes(v []TnPledgePledgeAttribute) {
	o.Attributes = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *TgvalidatordTnPledge) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *TgvalidatordTnPledge) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetExternalReferenceId returns the ExternalReferenceId field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetExternalReferenceId() string {
	if o == nil || IsNil(o.ExternalReferenceId) {
		var ret string
		return ret
	}
	return *o.ExternalReferenceId
}

// GetExternalReferenceIdOk returns a tuple with the ExternalReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetExternalReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalReferenceId) {
		return nil, false
	}
	return o.ExternalReferenceId, true
}

// HasExternalReferenceId returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasExternalReferenceId() bool {
	if o != nil && !IsNil(o.ExternalReferenceId) {
		return true
	}

	return false
}

// SetExternalReferenceId gets a reference to the given string and assigns it to the ExternalReferenceId field.
func (o *TgvalidatordTnPledge) SetExternalReferenceId(v string) {
	o.ExternalReferenceId = &v
}

// GetReconciliationNote returns the ReconciliationNote field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetReconciliationNote() string {
	if o == nil || IsNil(o.ReconciliationNote) {
		var ret string
		return ret
	}
	return *o.ReconciliationNote
}

// GetReconciliationNoteOk returns a tuple with the ReconciliationNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetReconciliationNoteOk() (*string, bool) {
	if o == nil || IsNil(o.ReconciliationNote) {
		return nil, false
	}
	return o.ReconciliationNote, true
}

// HasReconciliationNote returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasReconciliationNote() bool {
	if o != nil && !IsNil(o.ReconciliationNote) {
		return true
	}

	return false
}

// SetReconciliationNote gets a reference to the given string and assigns it to the ReconciliationNote field.
func (o *TgvalidatordTnPledge) SetReconciliationNote(v string) {
	o.ReconciliationNote = &v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetDirection() string {
	if o == nil || IsNil(o.Direction) {
		var ret string
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given string and assigns it to the Direction field.
func (o *TgvalidatordTnPledge) SetDirection(v string) {
	o.Direction = &v
}

// GetWladdressID returns the WladdressID field value if set, zero value otherwise.
func (o *TgvalidatordTnPledge) GetWladdressID() string {
	if o == nil || IsNil(o.WladdressID) {
		var ret string
		return ret
	}
	return *o.WladdressID
}

// GetWladdressIDOk returns a tuple with the WladdressID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTnPledge) GetWladdressIDOk() (*string, bool) {
	if o == nil || IsNil(o.WladdressID) {
		return nil, false
	}
	return o.WladdressID, true
}

// HasWladdressID returns a boolean if a field has been set.
func (o *TgvalidatordTnPledge) HasWladdressID() bool {
	if o != nil && !IsNil(o.WladdressID) {
		return true
	}

	return false
}

// SetWladdressID gets a reference to the given string and assigns it to the WladdressID field.
func (o *TgvalidatordTnPledge) SetWladdressID(v string) {
	o.WladdressID = &v
}

func (o TgvalidatordTnPledge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TgvalidatordTnPledge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.SharedAddressID) {
		toSerialize["sharedAddressID"] = o.SharedAddressID
	}
	if !IsNil(o.OwnerParticipantID) {
		toSerialize["ownerParticipantID"] = o.OwnerParticipantID
	}
	if !IsNil(o.TargetParticipantID) {
		toSerialize["targetParticipantID"] = o.TargetParticipantID
	}
	if !IsNil(o.CurrencyID) {
		toSerialize["currencyID"] = o.CurrencyID
	}
	if !IsNil(o.Blockchain) {
		toSerialize["blockchain"] = o.Blockchain
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.Arg1) {
		toSerialize["arg1"] = o.Arg1
	}
	if !IsNil(o.Arg2) {
		toSerialize["arg2"] = o.Arg2
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.PledgeType) {
		toSerialize["pledgeType"] = o.PledgeType
	}
	if !IsNil(o.Trails) {
		toSerialize["trails"] = o.Trails
	}
	if !IsNil(o.OriginCreationDate) {
		toSerialize["originCreationDate"] = o.OriginCreationDate
	}
	if !IsNil(o.DurationSetup) {
		toSerialize["durationSetup"] = o.DurationSetup
	}
	if !IsNil(o.UnpledgeDate) {
		toSerialize["unpledgeDate"] = o.UnpledgeDate
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.ExternalReferenceId) {
		toSerialize["externalReferenceId"] = o.ExternalReferenceId
	}
	if !IsNil(o.ReconciliationNote) {
		toSerialize["reconciliationNote"] = o.ReconciliationNote
	}
	if !IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !IsNil(o.WladdressID) {
		toSerialize["wladdressID"] = o.WladdressID
	}
	return toSerialize, nil
}

type NullableTgvalidatordTnPledge struct {
	value *TgvalidatordTnPledge
	isSet bool
}

func (v NullableTgvalidatordTnPledge) Get() *TgvalidatordTnPledge {
	return v.value
}

func (v *NullableTgvalidatordTnPledge) Set(val *TgvalidatordTnPledge) {
	v.value = val
	v.isSet = true
}

func (v NullableTgvalidatordTnPledge) IsSet() bool {
	return v.isSet
}

func (v *NullableTgvalidatordTnPledge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTgvalidatordTnPledge(val *TgvalidatordTnPledge) *NullableTgvalidatordTnPledge {
	return &NullableTgvalidatordTnPledge{value: val, isSet: true}
}

func (v NullableTgvalidatordTnPledge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTgvalidatordTnPledge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


