/*
Taurus-PROTECT APIs

Taurus-PROTECT APIs description

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the TgvalidatordTransaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TgvalidatordTransaction{}

// TgvalidatordTransaction struct for TgvalidatordTransaction
type TgvalidatordTransaction struct {
	// A unique identifier for the transaction
	Id *string `json:"id,omitempty"`
	// The direction of the transaction (e.g. `incoming`, `outgoing`)
	Direction *string `json:"direction,omitempty"`
	// The symbol or unique id of the currency the transaction used (e.g. `ETH`)
	Currency *string `json:"currency,omitempty"`
	// The addresses that sent currency for this transaction.
	Sources []TgvalidatordAddressInfo `json:"sources,omitempty"`
	// The addresses that received currency for this transaction.
	Destinations []TgvalidatordAddressInfo `json:"destinations,omitempty"`
	// Amount in the smallest currency unit, based on the currency decimals. Example: 1500000000000000000 WEI (smallest ETH unit) corresponds to 1.5 ETH (ETH has 18 decimals places)
	Amount *string `json:"amount,omitempty"`
	// Amount in the main currency unit (e.g. A BTC transaction will use the BTC value here instead of SAT)
	AmountMainUnit *string `json:"amountMainUnit,omitempty"`
	// The fee associated with the transaction if there is one. In the smallest currency unit.
	Fee *string `json:"fee,omitempty"`
	// The fee associated with the transaction if there is one. In the main currency unit. 
	FeeMainUnit *string `json:"feeMainUnit,omitempty"`
	// The hash of the transaction as returned by the chain.
	Hash *string `json:"hash,omitempty"`
	// The block number associated with the transaction.
	Block *string `json:"block,omitempty"`
	// When the transaction was received by the blockchain.
	ReceptionDate *time.Time `json:"receptionDate,omitempty"`
	// When the transaction was fully confirmed.
	ConfirmationDate *time.Time `json:"confirmationDate,omitempty"`
	// An id for the transaction.
	TransactionId *string `json:"transactionId,omitempty"`
	// The type of transaction occurring (e.g. `burn`, `approve`).
	Type *string `json:"type,omitempty"`
	// A unique id for the transaction.
	UniqueId *string `json:"uniqueId,omitempty"`
	// The blockchain associated with the transaction (e.g. `ETH`, `BTC`)
	Blockchain *string `json:"blockchain,omitempty"`
	// If set, serves as a sub-identifier to the blockchain field for the type of resource this transaction relates to. Typically a contract address.
	Arg1 *string `json:"arg1,omitempty"`
	// If set, serves as a sub-identifier to the arg1 field for the type of resource this transaction relates to. Typically a token ID.
	Arg2 *string `json:"arg2,omitempty"`
	CurrencyInfo *TgvalidatordCurrency `json:"currencyInfo,omitempty"`
	// The network the transaction took place in (e.g. `mainnet`, `testnet`).
	Network *string `json:"network,omitempty"`
	// If set, contains the request ID that this transaction originated from.
	RequestId *string `json:"requestId,omitempty"`
	// The block that the transaction was confirmed by.
	ConfirmationBlock *string `json:"confirmationBlock,omitempty"`
	// Indicates whether the requestId value refers to a request that is visible to the user.
	RequestVisible *bool `json:"requestVisible,omitempty"`
	TravelRule *TgvalidatordTravelRule `json:"travelRule,omitempty"`
	// The current status of the transaction, [`NEW`, `SUCCESS`, `PENDING`, `TEMPORARY_FAILURE`, `INVALID`, `TIMEOUT`, `MINED`, `LOST`, `EXPIRED`]
	Status *string `json:"status,omitempty"`
	// Any Platform fees on the transaction such as exchange withdrawals.
	PlatformFees []TgvalidatordPlatformFee `json:"platformFees,omitempty"`
	// A list of key-value transaction attributes.
	Attributes []TgvalidatordTransactionAttribute `json:"attributes,omitempty"`
	// The forkNumber is used in case a blockchain uses a new platform and starts over with a new genesis hash. For instance it is set to 1 on the new DOT AssetHub platform, otherwise it is 0 in most cases.
	ForkNumber *string `json:"forkNumber,omitempty"`
	// List of the fees of the transaction with corresponding assets.
	Fees []TgvalidatordTransactionFees `json:"fees,omitempty"`
	// True if the transaction is fully confirmed, false otherwise.
	IsConfirmed *bool `json:"isConfirmed,omitempty"`
}

// NewTgvalidatordTransaction instantiates a new TgvalidatordTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTgvalidatordTransaction() *TgvalidatordTransaction {
	this := TgvalidatordTransaction{}
	return &this
}

// NewTgvalidatordTransactionWithDefaults instantiates a new TgvalidatordTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTgvalidatordTransactionWithDefaults() *TgvalidatordTransaction {
	this := TgvalidatordTransaction{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TgvalidatordTransaction) SetId(v string) {
	o.Id = &v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetDirection() string {
	if o == nil || IsNil(o.Direction) {
		var ret string
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given string and assigns it to the Direction field.
func (o *TgvalidatordTransaction) SetDirection(v string) {
	o.Direction = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *TgvalidatordTransaction) SetCurrency(v string) {
	o.Currency = &v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetSources() []TgvalidatordAddressInfo {
	if o == nil || IsNil(o.Sources) {
		var ret []TgvalidatordAddressInfo
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetSourcesOk() ([]TgvalidatordAddressInfo, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given []TgvalidatordAddressInfo and assigns it to the Sources field.
func (o *TgvalidatordTransaction) SetSources(v []TgvalidatordAddressInfo) {
	o.Sources = v
}

// GetDestinations returns the Destinations field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetDestinations() []TgvalidatordAddressInfo {
	if o == nil || IsNil(o.Destinations) {
		var ret []TgvalidatordAddressInfo
		return ret
	}
	return o.Destinations
}

// GetDestinationsOk returns a tuple with the Destinations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetDestinationsOk() ([]TgvalidatordAddressInfo, bool) {
	if o == nil || IsNil(o.Destinations) {
		return nil, false
	}
	return o.Destinations, true
}

// HasDestinations returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasDestinations() bool {
	if o != nil && !IsNil(o.Destinations) {
		return true
	}

	return false
}

// SetDestinations gets a reference to the given []TgvalidatordAddressInfo and assigns it to the Destinations field.
func (o *TgvalidatordTransaction) SetDestinations(v []TgvalidatordAddressInfo) {
	o.Destinations = v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *TgvalidatordTransaction) SetAmount(v string) {
	o.Amount = &v
}

// GetAmountMainUnit returns the AmountMainUnit field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetAmountMainUnit() string {
	if o == nil || IsNil(o.AmountMainUnit) {
		var ret string
		return ret
	}
	return *o.AmountMainUnit
}

// GetAmountMainUnitOk returns a tuple with the AmountMainUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetAmountMainUnitOk() (*string, bool) {
	if o == nil || IsNil(o.AmountMainUnit) {
		return nil, false
	}
	return o.AmountMainUnit, true
}

// HasAmountMainUnit returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasAmountMainUnit() bool {
	if o != nil && !IsNil(o.AmountMainUnit) {
		return true
	}

	return false
}

// SetAmountMainUnit gets a reference to the given string and assigns it to the AmountMainUnit field.
func (o *TgvalidatordTransaction) SetAmountMainUnit(v string) {
	o.AmountMainUnit = &v
}

// GetFee returns the Fee field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetFee() string {
	if o == nil || IsNil(o.Fee) {
		var ret string
		return ret
	}
	return *o.Fee
}

// GetFeeOk returns a tuple with the Fee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetFeeOk() (*string, bool) {
	if o == nil || IsNil(o.Fee) {
		return nil, false
	}
	return o.Fee, true
}

// HasFee returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasFee() bool {
	if o != nil && !IsNil(o.Fee) {
		return true
	}

	return false
}

// SetFee gets a reference to the given string and assigns it to the Fee field.
func (o *TgvalidatordTransaction) SetFee(v string) {
	o.Fee = &v
}

// GetFeeMainUnit returns the FeeMainUnit field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetFeeMainUnit() string {
	if o == nil || IsNil(o.FeeMainUnit) {
		var ret string
		return ret
	}
	return *o.FeeMainUnit
}

// GetFeeMainUnitOk returns a tuple with the FeeMainUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetFeeMainUnitOk() (*string, bool) {
	if o == nil || IsNil(o.FeeMainUnit) {
		return nil, false
	}
	return o.FeeMainUnit, true
}

// HasFeeMainUnit returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasFeeMainUnit() bool {
	if o != nil && !IsNil(o.FeeMainUnit) {
		return true
	}

	return false
}

// SetFeeMainUnit gets a reference to the given string and assigns it to the FeeMainUnit field.
func (o *TgvalidatordTransaction) SetFeeMainUnit(v string) {
	o.FeeMainUnit = &v
}

// GetHash returns the Hash field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetHash() string {
	if o == nil || IsNil(o.Hash) {
		var ret string
		return ret
	}
	return *o.Hash
}

// GetHashOk returns a tuple with the Hash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetHashOk() (*string, bool) {
	if o == nil || IsNil(o.Hash) {
		return nil, false
	}
	return o.Hash, true
}

// HasHash returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasHash() bool {
	if o != nil && !IsNil(o.Hash) {
		return true
	}

	return false
}

// SetHash gets a reference to the given string and assigns it to the Hash field.
func (o *TgvalidatordTransaction) SetHash(v string) {
	o.Hash = &v
}

// GetBlock returns the Block field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetBlock() string {
	if o == nil || IsNil(o.Block) {
		var ret string
		return ret
	}
	return *o.Block
}

// GetBlockOk returns a tuple with the Block field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetBlockOk() (*string, bool) {
	if o == nil || IsNil(o.Block) {
		return nil, false
	}
	return o.Block, true
}

// HasBlock returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasBlock() bool {
	if o != nil && !IsNil(o.Block) {
		return true
	}

	return false
}

// SetBlock gets a reference to the given string and assigns it to the Block field.
func (o *TgvalidatordTransaction) SetBlock(v string) {
	o.Block = &v
}

// GetReceptionDate returns the ReceptionDate field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetReceptionDate() time.Time {
	if o == nil || IsNil(o.ReceptionDate) {
		var ret time.Time
		return ret
	}
	return *o.ReceptionDate
}

// GetReceptionDateOk returns a tuple with the ReceptionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetReceptionDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ReceptionDate) {
		return nil, false
	}
	return o.ReceptionDate, true
}

// HasReceptionDate returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasReceptionDate() bool {
	if o != nil && !IsNil(o.ReceptionDate) {
		return true
	}

	return false
}

// SetReceptionDate gets a reference to the given time.Time and assigns it to the ReceptionDate field.
func (o *TgvalidatordTransaction) SetReceptionDate(v time.Time) {
	o.ReceptionDate = &v
}

// GetConfirmationDate returns the ConfirmationDate field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetConfirmationDate() time.Time {
	if o == nil || IsNil(o.ConfirmationDate) {
		var ret time.Time
		return ret
	}
	return *o.ConfirmationDate
}

// GetConfirmationDateOk returns a tuple with the ConfirmationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetConfirmationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ConfirmationDate) {
		return nil, false
	}
	return o.ConfirmationDate, true
}

// HasConfirmationDate returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasConfirmationDate() bool {
	if o != nil && !IsNil(o.ConfirmationDate) {
		return true
	}

	return false
}

// SetConfirmationDate gets a reference to the given time.Time and assigns it to the ConfirmationDate field.
func (o *TgvalidatordTransaction) SetConfirmationDate(v time.Time) {
	o.ConfirmationDate = &v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *TgvalidatordTransaction) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TgvalidatordTransaction) SetType(v string) {
	o.Type = &v
}

// GetUniqueId returns the UniqueId field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetUniqueId() string {
	if o == nil || IsNil(o.UniqueId) {
		var ret string
		return ret
	}
	return *o.UniqueId
}

// GetUniqueIdOk returns a tuple with the UniqueId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetUniqueIdOk() (*string, bool) {
	if o == nil || IsNil(o.UniqueId) {
		return nil, false
	}
	return o.UniqueId, true
}

// HasUniqueId returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasUniqueId() bool {
	if o != nil && !IsNil(o.UniqueId) {
		return true
	}

	return false
}

// SetUniqueId gets a reference to the given string and assigns it to the UniqueId field.
func (o *TgvalidatordTransaction) SetUniqueId(v string) {
	o.UniqueId = &v
}

// GetBlockchain returns the Blockchain field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetBlockchain() string {
	if o == nil || IsNil(o.Blockchain) {
		var ret string
		return ret
	}
	return *o.Blockchain
}

// GetBlockchainOk returns a tuple with the Blockchain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetBlockchainOk() (*string, bool) {
	if o == nil || IsNil(o.Blockchain) {
		return nil, false
	}
	return o.Blockchain, true
}

// HasBlockchain returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasBlockchain() bool {
	if o != nil && !IsNil(o.Blockchain) {
		return true
	}

	return false
}

// SetBlockchain gets a reference to the given string and assigns it to the Blockchain field.
func (o *TgvalidatordTransaction) SetBlockchain(v string) {
	o.Blockchain = &v
}

// GetArg1 returns the Arg1 field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetArg1() string {
	if o == nil || IsNil(o.Arg1) {
		var ret string
		return ret
	}
	return *o.Arg1
}

// GetArg1Ok returns a tuple with the Arg1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetArg1Ok() (*string, bool) {
	if o == nil || IsNil(o.Arg1) {
		return nil, false
	}
	return o.Arg1, true
}

// HasArg1 returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasArg1() bool {
	if o != nil && !IsNil(o.Arg1) {
		return true
	}

	return false
}

// SetArg1 gets a reference to the given string and assigns it to the Arg1 field.
func (o *TgvalidatordTransaction) SetArg1(v string) {
	o.Arg1 = &v
}

// GetArg2 returns the Arg2 field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetArg2() string {
	if o == nil || IsNil(o.Arg2) {
		var ret string
		return ret
	}
	return *o.Arg2
}

// GetArg2Ok returns a tuple with the Arg2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetArg2Ok() (*string, bool) {
	if o == nil || IsNil(o.Arg2) {
		return nil, false
	}
	return o.Arg2, true
}

// HasArg2 returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasArg2() bool {
	if o != nil && !IsNil(o.Arg2) {
		return true
	}

	return false
}

// SetArg2 gets a reference to the given string and assigns it to the Arg2 field.
func (o *TgvalidatordTransaction) SetArg2(v string) {
	o.Arg2 = &v
}

// GetCurrencyInfo returns the CurrencyInfo field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetCurrencyInfo() TgvalidatordCurrency {
	if o == nil || IsNil(o.CurrencyInfo) {
		var ret TgvalidatordCurrency
		return ret
	}
	return *o.CurrencyInfo
}

// GetCurrencyInfoOk returns a tuple with the CurrencyInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetCurrencyInfoOk() (*TgvalidatordCurrency, bool) {
	if o == nil || IsNil(o.CurrencyInfo) {
		return nil, false
	}
	return o.CurrencyInfo, true
}

// HasCurrencyInfo returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasCurrencyInfo() bool {
	if o != nil && !IsNil(o.CurrencyInfo) {
		return true
	}

	return false
}

// SetCurrencyInfo gets a reference to the given TgvalidatordCurrency and assigns it to the CurrencyInfo field.
func (o *TgvalidatordTransaction) SetCurrencyInfo(v TgvalidatordCurrency) {
	o.CurrencyInfo = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *TgvalidatordTransaction) SetNetwork(v string) {
	o.Network = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *TgvalidatordTransaction) SetRequestId(v string) {
	o.RequestId = &v
}

// GetConfirmationBlock returns the ConfirmationBlock field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetConfirmationBlock() string {
	if o == nil || IsNil(o.ConfirmationBlock) {
		var ret string
		return ret
	}
	return *o.ConfirmationBlock
}

// GetConfirmationBlockOk returns a tuple with the ConfirmationBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetConfirmationBlockOk() (*string, bool) {
	if o == nil || IsNil(o.ConfirmationBlock) {
		return nil, false
	}
	return o.ConfirmationBlock, true
}

// HasConfirmationBlock returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasConfirmationBlock() bool {
	if o != nil && !IsNil(o.ConfirmationBlock) {
		return true
	}

	return false
}

// SetConfirmationBlock gets a reference to the given string and assigns it to the ConfirmationBlock field.
func (o *TgvalidatordTransaction) SetConfirmationBlock(v string) {
	o.ConfirmationBlock = &v
}

// GetRequestVisible returns the RequestVisible field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetRequestVisible() bool {
	if o == nil || IsNil(o.RequestVisible) {
		var ret bool
		return ret
	}
	return *o.RequestVisible
}

// GetRequestVisibleOk returns a tuple with the RequestVisible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetRequestVisibleOk() (*bool, bool) {
	if o == nil || IsNil(o.RequestVisible) {
		return nil, false
	}
	return o.RequestVisible, true
}

// HasRequestVisible returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasRequestVisible() bool {
	if o != nil && !IsNil(o.RequestVisible) {
		return true
	}

	return false
}

// SetRequestVisible gets a reference to the given bool and assigns it to the RequestVisible field.
func (o *TgvalidatordTransaction) SetRequestVisible(v bool) {
	o.RequestVisible = &v
}

// GetTravelRule returns the TravelRule field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetTravelRule() TgvalidatordTravelRule {
	if o == nil || IsNil(o.TravelRule) {
		var ret TgvalidatordTravelRule
		return ret
	}
	return *o.TravelRule
}

// GetTravelRuleOk returns a tuple with the TravelRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetTravelRuleOk() (*TgvalidatordTravelRule, bool) {
	if o == nil || IsNil(o.TravelRule) {
		return nil, false
	}
	return o.TravelRule, true
}

// HasTravelRule returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasTravelRule() bool {
	if o != nil && !IsNil(o.TravelRule) {
		return true
	}

	return false
}

// SetTravelRule gets a reference to the given TgvalidatordTravelRule and assigns it to the TravelRule field.
func (o *TgvalidatordTransaction) SetTravelRule(v TgvalidatordTravelRule) {
	o.TravelRule = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TgvalidatordTransaction) SetStatus(v string) {
	o.Status = &v
}

// GetPlatformFees returns the PlatformFees field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetPlatformFees() []TgvalidatordPlatformFee {
	if o == nil || IsNil(o.PlatformFees) {
		var ret []TgvalidatordPlatformFee
		return ret
	}
	return o.PlatformFees
}

// GetPlatformFeesOk returns a tuple with the PlatformFees field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetPlatformFeesOk() ([]TgvalidatordPlatformFee, bool) {
	if o == nil || IsNil(o.PlatformFees) {
		return nil, false
	}
	return o.PlatformFees, true
}

// HasPlatformFees returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasPlatformFees() bool {
	if o != nil && !IsNil(o.PlatformFees) {
		return true
	}

	return false
}

// SetPlatformFees gets a reference to the given []TgvalidatordPlatformFee and assigns it to the PlatformFees field.
func (o *TgvalidatordTransaction) SetPlatformFees(v []TgvalidatordPlatformFee) {
	o.PlatformFees = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetAttributes() []TgvalidatordTransactionAttribute {
	if o == nil || IsNil(o.Attributes) {
		var ret []TgvalidatordTransactionAttribute
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetAttributesOk() ([]TgvalidatordTransactionAttribute, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []TgvalidatordTransactionAttribute and assigns it to the Attributes field.
func (o *TgvalidatordTransaction) SetAttributes(v []TgvalidatordTransactionAttribute) {
	o.Attributes = v
}

// GetForkNumber returns the ForkNumber field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetForkNumber() string {
	if o == nil || IsNil(o.ForkNumber) {
		var ret string
		return ret
	}
	return *o.ForkNumber
}

// GetForkNumberOk returns a tuple with the ForkNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetForkNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ForkNumber) {
		return nil, false
	}
	return o.ForkNumber, true
}

// HasForkNumber returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasForkNumber() bool {
	if o != nil && !IsNil(o.ForkNumber) {
		return true
	}

	return false
}

// SetForkNumber gets a reference to the given string and assigns it to the ForkNumber field.
func (o *TgvalidatordTransaction) SetForkNumber(v string) {
	o.ForkNumber = &v
}

// GetFees returns the Fees field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetFees() []TgvalidatordTransactionFees {
	if o == nil || IsNil(o.Fees) {
		var ret []TgvalidatordTransactionFees
		return ret
	}
	return o.Fees
}

// GetFeesOk returns a tuple with the Fees field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetFeesOk() ([]TgvalidatordTransactionFees, bool) {
	if o == nil || IsNil(o.Fees) {
		return nil, false
	}
	return o.Fees, true
}

// HasFees returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasFees() bool {
	if o != nil && !IsNil(o.Fees) {
		return true
	}

	return false
}

// SetFees gets a reference to the given []TgvalidatordTransactionFees and assigns it to the Fees field.
func (o *TgvalidatordTransaction) SetFees(v []TgvalidatordTransactionFees) {
	o.Fees = v
}

// GetIsConfirmed returns the IsConfirmed field value if set, zero value otherwise.
func (o *TgvalidatordTransaction) GetIsConfirmed() bool {
	if o == nil || IsNil(o.IsConfirmed) {
		var ret bool
		return ret
	}
	return *o.IsConfirmed
}

// GetIsConfirmedOk returns a tuple with the IsConfirmed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TgvalidatordTransaction) GetIsConfirmedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsConfirmed) {
		return nil, false
	}
	return o.IsConfirmed, true
}

// HasIsConfirmed returns a boolean if a field has been set.
func (o *TgvalidatordTransaction) HasIsConfirmed() bool {
	if o != nil && !IsNil(o.IsConfirmed) {
		return true
	}

	return false
}

// SetIsConfirmed gets a reference to the given bool and assigns it to the IsConfirmed field.
func (o *TgvalidatordTransaction) SetIsConfirmed(v bool) {
	o.IsConfirmed = &v
}

func (o TgvalidatordTransaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TgvalidatordTransaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	if !IsNil(o.Destinations) {
		toSerialize["destinations"] = o.Destinations
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.AmountMainUnit) {
		toSerialize["amountMainUnit"] = o.AmountMainUnit
	}
	if !IsNil(o.Fee) {
		toSerialize["fee"] = o.Fee
	}
	if !IsNil(o.FeeMainUnit) {
		toSerialize["feeMainUnit"] = o.FeeMainUnit
	}
	if !IsNil(o.Hash) {
		toSerialize["hash"] = o.Hash
	}
	if !IsNil(o.Block) {
		toSerialize["block"] = o.Block
	}
	if !IsNil(o.ReceptionDate) {
		toSerialize["receptionDate"] = o.ReceptionDate
	}
	if !IsNil(o.ConfirmationDate) {
		toSerialize["confirmationDate"] = o.ConfirmationDate
	}
	if !IsNil(o.TransactionId) {
		toSerialize["transactionId"] = o.TransactionId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UniqueId) {
		toSerialize["uniqueId"] = o.UniqueId
	}
	if !IsNil(o.Blockchain) {
		toSerialize["blockchain"] = o.Blockchain
	}
	if !IsNil(o.Arg1) {
		toSerialize["arg1"] = o.Arg1
	}
	if !IsNil(o.Arg2) {
		toSerialize["arg2"] = o.Arg2
	}
	if !IsNil(o.CurrencyInfo) {
		toSerialize["currencyInfo"] = o.CurrencyInfo
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.ConfirmationBlock) {
		toSerialize["confirmationBlock"] = o.ConfirmationBlock
	}
	if !IsNil(o.RequestVisible) {
		toSerialize["requestVisible"] = o.RequestVisible
	}
	if !IsNil(o.TravelRule) {
		toSerialize["travelRule"] = o.TravelRule
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.PlatformFees) {
		toSerialize["platformFees"] = o.PlatformFees
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.ForkNumber) {
		toSerialize["forkNumber"] = o.ForkNumber
	}
	if !IsNil(o.Fees) {
		toSerialize["fees"] = o.Fees
	}
	if !IsNil(o.IsConfirmed) {
		toSerialize["isConfirmed"] = o.IsConfirmed
	}
	return toSerialize, nil
}

type NullableTgvalidatordTransaction struct {
	value *TgvalidatordTransaction
	isSet bool
}

func (v NullableTgvalidatordTransaction) Get() *TgvalidatordTransaction {
	return v.value
}

func (v *NullableTgvalidatordTransaction) Set(val *TgvalidatordTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableTgvalidatordTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableTgvalidatordTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTgvalidatordTransaction(val *TgvalidatordTransaction) *NullableTgvalidatordTransaction {
	return &NullableTgvalidatordTransaction{value: val, isSet: true}
}

func (v NullableTgvalidatordTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTgvalidatordTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


