/*
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.taurushq.sdk.protect.openapi.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets GetICPNeuronInfoReplyNeuronState
 * <p>
 * An open set of values: a value this client was not generated with is kept as-is, so
 * {@link #fromValue} never throws and a new server value cannot fail a whole decode.
 */
@JsonAdapter(GetICPNeuronInfoReplyNeuronState.Adapter.class)
public final class GetICPNeuronInfoReplyNeuronState {
  
  public static final GetICPNeuronInfoReplyNeuronState NEURON_STATE_NOT_DISSOLVING = new GetICPNeuronInfoReplyNeuronState("NeuronStateNotDissolving");
  
  public static final GetICPNeuronInfoReplyNeuronState NEURON_STATE_DISSOLVING = new GetICPNeuronInfoReplyNeuronState("NeuronStateDissolving");
  
  public static final GetICPNeuronInfoReplyNeuronState NEURON_STATE_DISSOLVED = new GetICPNeuronInfoReplyNeuronState("NeuronStateDissolved");
  
  public static final GetICPNeuronInfoReplyNeuronState NEURON_STATE_SPAWNING = new GetICPNeuronInfoReplyNeuronState("NeuronStateSpawning");
  

  private static final GetICPNeuronInfoReplyNeuronState[] knownValues = { NEURON_STATE_NOT_DISSOLVING, NEURON_STATE_DISSOLVING, NEURON_STATE_DISSOLVED, NEURON_STATE_SPAWNING };

  private final String value;

  private GetICPNeuronInfoReplyNeuronState(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  /**
   * Returns the values this client was generated with.
   *
   * @return a new array of the known values
   */
  public static GetICPNeuronInfoReplyNeuronState[] values() {
    return knownValues.clone();
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return Objects.equals(value, ((GetICPNeuronInfoReplyNeuronState) o).value);
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(value);
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  /**
   * Returns the known constant for a value, or a new instance carrying a value this client
   * does not know. Never throws.
   *
   * @param value the wire value
   * @return the matching instance, or null for a null value
   */
  public static GetICPNeuronInfoReplyNeuronState fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (GetICPNeuronInfoReplyNeuronState b : knownValues) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return new GetICPNeuronInfoReplyNeuronState(value);
  }

  public static class Adapter extends TypeAdapter<GetICPNeuronInfoReplyNeuronState> {
    @Override
    public void write(final JsonWriter jsonWriter, final GetICPNeuronInfoReplyNeuronState enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public GetICPNeuronInfoReplyNeuronState read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return GetICPNeuronInfoReplyNeuronState.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    GetICPNeuronInfoReplyNeuronState.fromValue(value);
  }
}

