/*
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.taurushq.sdk.protect.openapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.taurushq.sdk.protect.openapi.JSON;

/**
 * TgvalidatordCreateOutgoingUTXOsRequestRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-23T15:56:06.931912+01:00[Europe/Zurich]", comments = "Generator version: 7.9.0")
public class TgvalidatordCreateOutgoingUTXOsRequestRequest {
  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private String amount;

  public static final String SERIALIZED_NAME_FEE_LIMIT = "feeLimit";
  @SerializedName(SERIALIZED_NAME_FEE_LIMIT)
  private String feeLimit;

  public static final String SERIALIZED_NAME_FROM_ADDRESS_ID = "fromAddressId";
  @SerializedName(SERIALIZED_NAME_FROM_ADDRESS_ID)
  private String fromAddressId;

  public static final String SERIALIZED_NAME_TO_ADDRESS_ID = "toAddressId";
  @SerializedName(SERIALIZED_NAME_TO_ADDRESS_ID)
  private String toAddressId;

  public static final String SERIALIZED_NAME_TO_WHITELISTED_ADDRESS_ID = "toWhitelistedAddressId";
  @SerializedName(SERIALIZED_NAME_TO_WHITELISTED_ADDRESS_ID)
  private String toWhitelistedAddressId;

  public static final String SERIALIZED_NAME_UTXO_IDS = "utxoIds";
  @SerializedName(SERIALIZED_NAME_UTXO_IDS)
  private List<String> utxoIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;

  public static final String SERIALIZED_NAME_FEE_PAID_BY_RECEIVER = "feePaidByReceiver";
  @SerializedName(SERIALIZED_NAME_FEE_PAID_BY_RECEIVER)
  private Boolean feePaidByReceiver;

  public static final String SERIALIZED_NAME_TRANSACTION_REFERENCE = "transactionReference";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_REFERENCE)
  private String transactionReference;

  public static final String SERIALIZED_NAME_EXTERNAL_REQUEST_ID = "externalRequestId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_REQUEST_ID)
  private String externalRequestId;

  public TgvalidatordCreateOutgoingUTXOsRequestRequest() {
  }

  public TgvalidatordCreateOutgoingUTXOsRequestRequest amount(String amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Amount in the smallest currency unit, based on the currency decimals. Example: 100000000 satoshi (smallest BTC unit) corresponds to 1 BTC (BTC has 8 decimals places)
   * @return amount
   */
  @javax.annotation.Nonnull
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }


  public TgvalidatordCreateOutgoingUTXOsRequestRequest feeLimit(String feeLimit) {
    this.feeLimit = feeLimit;
    return this;
  }

  /**
   * Get feeLimit
   * @return feeLimit
   */
  @javax.annotation.Nullable
  public String getFeeLimit() {
    return feeLimit;
  }

  public void setFeeLimit(String feeLimit) {
    this.feeLimit = feeLimit;
  }


  public TgvalidatordCreateOutgoingUTXOsRequestRequest fromAddressId(String fromAddressId) {
    this.fromAddressId = fromAddressId;
    return this;
  }

  /**
   * Get fromAddressId
   * @return fromAddressId
   */
  @javax.annotation.Nonnull
  public String getFromAddressId() {
    return fromAddressId;
  }

  public void setFromAddressId(String fromAddressId) {
    this.fromAddressId = fromAddressId;
  }


  public TgvalidatordCreateOutgoingUTXOsRequestRequest toAddressId(String toAddressId) {
    this.toAddressId = toAddressId;
    return this;
  }

  /**
   * Get toAddressId
   * @return toAddressId
   */
  @javax.annotation.Nullable
  public String getToAddressId() {
    return toAddressId;
  }

  public void setToAddressId(String toAddressId) {
    this.toAddressId = toAddressId;
  }


  public TgvalidatordCreateOutgoingUTXOsRequestRequest toWhitelistedAddressId(String toWhitelistedAddressId) {
    this.toWhitelistedAddressId = toWhitelistedAddressId;
    return this;
  }

  /**
   * Get toWhitelistedAddressId
   * @return toWhitelistedAddressId
   */
  @javax.annotation.Nullable
  public String getToWhitelistedAddressId() {
    return toWhitelistedAddressId;
  }

  public void setToWhitelistedAddressId(String toWhitelistedAddressId) {
    this.toWhitelistedAddressId = toWhitelistedAddressId;
  }


  public TgvalidatordCreateOutgoingUTXOsRequestRequest utxoIds(List<String> utxoIds) {
    this.utxoIds = utxoIds;
    return this;
  }

  public TgvalidatordCreateOutgoingUTXOsRequestRequest addUtxoIdsItem(String utxoIdsItem) {
    if (this.utxoIds == null) {
      this.utxoIds = new ArrayList<>();
    }
    this.utxoIds.add(utxoIdsItem);
    return this;
  }

  /**
   * Get utxoIds
   * @return utxoIds
   */
  @javax.annotation.Nonnull
  public List<String> getUtxoIds() {
    return utxoIds;
  }

  public void setUtxoIds(List<String> utxoIds) {
    this.utxoIds = utxoIds;
  }


  public TgvalidatordCreateOutgoingUTXOsRequestRequest comment(String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * string; A reconciliation note can be given when initiating a request and this will be included in transaction history.
   * @return comment
   */
  @javax.annotation.Nullable
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }


  public TgvalidatordCreateOutgoingUTXOsRequestRequest feePaidByReceiver(Boolean feePaidByReceiver) {
    this.feePaidByReceiver = feePaidByReceiver;
    return this;
  }

  /**
   * If &#x60;true&#x60;, maximum &#x60;amount&#x60; of funds will be transferred, including fees. When &#x60;false&#x60;, fees are added on top of &#x60;amount&#x60;.
   * @return feePaidByReceiver
   */
  @javax.annotation.Nullable
  public Boolean getFeePaidByReceiver() {
    return feePaidByReceiver;
  }

  public void setFeePaidByReceiver(Boolean feePaidByReceiver) {
    this.feePaidByReceiver = feePaidByReceiver;
  }


  public TgvalidatordCreateOutgoingUTXOsRequestRequest transactionReference(String transactionReference) {
    this.transactionReference = transactionReference;
    return this;
  }

  /**
   * **Deprecated:** use &#x60;externalRequestId&#x60; instead
   * @return transactionReference
   */
  @javax.annotation.Nullable
  public String getTransactionReference() {
    return transactionReference;
  }

  public void setTransactionReference(String transactionReference) {
    this.transactionReference = transactionReference;
  }


  public TgvalidatordCreateOutgoingUTXOsRequestRequest externalRequestId(String externalRequestId) {
    this.externalRequestId = externalRequestId;
    return this;
  }

  /**
   * Identifier for the request in the user&#39;s system. This must be unique. Attempting to create a request with an existing externalRequestId will do nothing and return the originally created request
   * @return externalRequestId
   */
  @javax.annotation.Nullable
  public String getExternalRequestId() {
    return externalRequestId;
  }

  public void setExternalRequestId(String externalRequestId) {
    this.externalRequestId = externalRequestId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TgvalidatordCreateOutgoingUTXOsRequestRequest instance itself
   */
  public TgvalidatordCreateOutgoingUTXOsRequestRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TgvalidatordCreateOutgoingUTXOsRequestRequest tgvalidatordCreateOutgoingUTXOsRequestRequest = (TgvalidatordCreateOutgoingUTXOsRequestRequest) o;
    return Objects.equals(this.amount, tgvalidatordCreateOutgoingUTXOsRequestRequest.amount) &&
        Objects.equals(this.feeLimit, tgvalidatordCreateOutgoingUTXOsRequestRequest.feeLimit) &&
        Objects.equals(this.fromAddressId, tgvalidatordCreateOutgoingUTXOsRequestRequest.fromAddressId) &&
        Objects.equals(this.toAddressId, tgvalidatordCreateOutgoingUTXOsRequestRequest.toAddressId) &&
        Objects.equals(this.toWhitelistedAddressId, tgvalidatordCreateOutgoingUTXOsRequestRequest.toWhitelistedAddressId) &&
        Objects.equals(this.utxoIds, tgvalidatordCreateOutgoingUTXOsRequestRequest.utxoIds) &&
        Objects.equals(this.comment, tgvalidatordCreateOutgoingUTXOsRequestRequest.comment) &&
        Objects.equals(this.feePaidByReceiver, tgvalidatordCreateOutgoingUTXOsRequestRequest.feePaidByReceiver) &&
        Objects.equals(this.transactionReference, tgvalidatordCreateOutgoingUTXOsRequestRequest.transactionReference) &&
        Objects.equals(this.externalRequestId, tgvalidatordCreateOutgoingUTXOsRequestRequest.externalRequestId)&&
        Objects.equals(this.additionalProperties, tgvalidatordCreateOutgoingUTXOsRequestRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, feeLimit, fromAddressId, toAddressId, toWhitelistedAddressId, utxoIds, comment, feePaidByReceiver, transactionReference, externalRequestId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TgvalidatordCreateOutgoingUTXOsRequestRequest {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    feeLimit: ").append(toIndentedString(feeLimit)).append("\n");
    sb.append("    fromAddressId: ").append(toIndentedString(fromAddressId)).append("\n");
    sb.append("    toAddressId: ").append(toIndentedString(toAddressId)).append("\n");
    sb.append("    toWhitelistedAddressId: ").append(toIndentedString(toWhitelistedAddressId)).append("\n");
    sb.append("    utxoIds: ").append(toIndentedString(utxoIds)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    feePaidByReceiver: ").append(toIndentedString(feePaidByReceiver)).append("\n");
    sb.append("    transactionReference: ").append(toIndentedString(transactionReference)).append("\n");
    sb.append("    externalRequestId: ").append(toIndentedString(externalRequestId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("amount");
    openapiFields.add("feeLimit");
    openapiFields.add("fromAddressId");
    openapiFields.add("toAddressId");
    openapiFields.add("toWhitelistedAddressId");
    openapiFields.add("utxoIds");
    openapiFields.add("comment");
    openapiFields.add("feePaidByReceiver");
    openapiFields.add("transactionReference");
    openapiFields.add("externalRequestId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("amount");
    openapiRequiredFields.add("fromAddressId");
    openapiRequiredFields.add("utxoIds");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TgvalidatordCreateOutgoingUTXOsRequestRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TgvalidatordCreateOutgoingUTXOsRequestRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TgvalidatordCreateOutgoingUTXOsRequestRequest is not found in the empty JSON string", TgvalidatordCreateOutgoingUTXOsRequestRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TgvalidatordCreateOutgoingUTXOsRequestRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount").toString()));
      }
      if ((jsonObj.get("feeLimit") != null && !jsonObj.get("feeLimit").isJsonNull()) && !jsonObj.get("feeLimit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `feeLimit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("feeLimit").toString()));
      }
      if (!jsonObj.get("fromAddressId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fromAddressId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fromAddressId").toString()));
      }
      if ((jsonObj.get("toAddressId") != null && !jsonObj.get("toAddressId").isJsonNull()) && !jsonObj.get("toAddressId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `toAddressId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("toAddressId").toString()));
      }
      if ((jsonObj.get("toWhitelistedAddressId") != null && !jsonObj.get("toWhitelistedAddressId").isJsonNull()) && !jsonObj.get("toWhitelistedAddressId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `toWhitelistedAddressId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("toWhitelistedAddressId").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("utxoIds") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("utxoIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `utxoIds` to be an array in the JSON string but got `%s`", jsonObj.get("utxoIds").toString()));
      }
      if ((jsonObj.get("comment") != null && !jsonObj.get("comment").isJsonNull()) && !jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
      if ((jsonObj.get("transactionReference") != null && !jsonObj.get("transactionReference").isJsonNull()) && !jsonObj.get("transactionReference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transactionReference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionReference").toString()));
      }
      if ((jsonObj.get("externalRequestId") != null && !jsonObj.get("externalRequestId").isJsonNull()) && !jsonObj.get("externalRequestId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `externalRequestId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("externalRequestId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TgvalidatordCreateOutgoingUTXOsRequestRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TgvalidatordCreateOutgoingUTXOsRequestRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TgvalidatordCreateOutgoingUTXOsRequestRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TgvalidatordCreateOutgoingUTXOsRequestRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<TgvalidatordCreateOutgoingUTXOsRequestRequest>() {
           @Override
           public void write(JsonWriter out, TgvalidatordCreateOutgoingUTXOsRequestRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TgvalidatordCreateOutgoingUTXOsRequestRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             TgvalidatordCreateOutgoingUTXOsRequestRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TgvalidatordCreateOutgoingUTXOsRequestRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TgvalidatordCreateOutgoingUTXOsRequestRequest
   * @throws IOException if the JSON string is invalid with respect to TgvalidatordCreateOutgoingUTXOsRequestRequest
   */
  public static TgvalidatordCreateOutgoingUTXOsRequestRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TgvalidatordCreateOutgoingUTXOsRequestRequest.class);
  }

  /**
   * Convert an instance of TgvalidatordCreateOutgoingUTXOsRequestRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

