/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GooglerpcStatus,
  TgvalidatordCreateOutgoingXTZDelegateRequestRequest,
  TgvalidatordCreateOutgoingXTZStakeRequestRequest,
  TgvalidatordCreateOutgoingXTZUndelegateRequestRequest,
  TgvalidatordCreateOutgoingXTZUnstakeRequestRequest,
  TgvalidatordCreateRequestReply,
  TgvalidatordGetXTZBakerReply,
} from '../models/index';
import {
    GooglerpcStatusFromJSON,
    GooglerpcStatusToJSON,
    TgvalidatordCreateOutgoingXTZDelegateRequestRequestFromJSON,
    TgvalidatordCreateOutgoingXTZDelegateRequestRequestToJSON,
    TgvalidatordCreateOutgoingXTZStakeRequestRequestFromJSON,
    TgvalidatordCreateOutgoingXTZStakeRequestRequestToJSON,
    TgvalidatordCreateOutgoingXTZUndelegateRequestRequestFromJSON,
    TgvalidatordCreateOutgoingXTZUndelegateRequestRequestToJSON,
    TgvalidatordCreateOutgoingXTZUnstakeRequestRequestFromJSON,
    TgvalidatordCreateOutgoingXTZUnstakeRequestRequestToJSON,
    TgvalidatordCreateRequestReplyFromJSON,
    TgvalidatordCreateRequestReplyToJSON,
    TgvalidatordGetXTZBakerReplyFromJSON,
    TgvalidatordGetXTZBakerReplyToJSON,
} from '../models/index';

export interface RequestServiceCreateOutgoingXTZDelegateRequestRequest {
    body: TgvalidatordCreateOutgoingXTZDelegateRequestRequest;
}

export interface RequestServiceCreateOutgoingXTZStakeRequestRequest {
    body: TgvalidatordCreateOutgoingXTZStakeRequestRequest;
}

export interface RequestServiceCreateOutgoingXTZUndelegateRequestRequest {
    body: TgvalidatordCreateOutgoingXTZUndelegateRequestRequest;
}

export interface RequestServiceCreateOutgoingXTZUnstakeRequestRequest {
    body: TgvalidatordCreateOutgoingXTZUnstakeRequestRequest;
}

export interface XTZBakerServiceGetXTZBakerRequest {
    network: string;
    address: string;
}

/**
 * RequestsXTZApi - interface
 * 
 * @export
 * @interface RequestsXTZApiInterface
 */
export interface RequestsXTZApiInterface {
    /**
     * This endpoint creates an outgoing delegate request for XTZ.  Required role: **RequestCreator**. This API can be made idempotent by generating an ID for the Request beforehand and passing it as the externalRequestId attribute
     * @summary Create a delegate request
     * @param {TgvalidatordCreateOutgoingXTZDelegateRequestRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestsXTZApiInterface
     */
    requestServiceCreateOutgoingXTZDelegateRequestRaw(requestParameters: RequestServiceCreateOutgoingXTZDelegateRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordCreateRequestReply>>;

    /**
     * This endpoint creates an outgoing delegate request for XTZ.  Required role: **RequestCreator**. This API can be made idempotent by generating an ID for the Request beforehand and passing it as the externalRequestId attribute
     * Create a delegate request
     */
    requestServiceCreateOutgoingXTZDelegateRequest(requestParameters: RequestServiceCreateOutgoingXTZDelegateRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordCreateRequestReply>;

    /**
     * This endpoint creates an outgoing stake request for XTZ.  Required role: **RequestCreator**. This API can be made idempotent by generating an ID for the Request beforehand and passing it as the externalRequestId attribute
     * @summary Create a stake request
     * @param {TgvalidatordCreateOutgoingXTZStakeRequestRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestsXTZApiInterface
     */
    requestServiceCreateOutgoingXTZStakeRequestRaw(requestParameters: RequestServiceCreateOutgoingXTZStakeRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordCreateRequestReply>>;

    /**
     * This endpoint creates an outgoing stake request for XTZ.  Required role: **RequestCreator**. This API can be made idempotent by generating an ID for the Request beforehand and passing it as the externalRequestId attribute
     * Create a stake request
     */
    requestServiceCreateOutgoingXTZStakeRequest(requestParameters: RequestServiceCreateOutgoingXTZStakeRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordCreateRequestReply>;

    /**
     * This endpoint creates an outgoing undelegate request for XTZ.  Required role: **RequestCreator**.extractRequestEntity
     * @summary Create an undelegate request
     * @param {TgvalidatordCreateOutgoingXTZUndelegateRequestRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestsXTZApiInterface
     */
    requestServiceCreateOutgoingXTZUndelegateRequestRaw(requestParameters: RequestServiceCreateOutgoingXTZUndelegateRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordCreateRequestReply>>;

    /**
     * This endpoint creates an outgoing undelegate request for XTZ.  Required role: **RequestCreator**.extractRequestEntity
     * Create an undelegate request
     */
    requestServiceCreateOutgoingXTZUndelegateRequest(requestParameters: RequestServiceCreateOutgoingXTZUndelegateRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordCreateRequestReply>;

    /**
     * This endpoint creates an outgoing unstake request for XTZ.  Required role: **RequestCreator**.extractRequestEntity
     * @summary Create an unstake request
     * @param {TgvalidatordCreateOutgoingXTZUnstakeRequestRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestsXTZApiInterface
     */
    requestServiceCreateOutgoingXTZUnstakeRequestRaw(requestParameters: RequestServiceCreateOutgoingXTZUnstakeRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordCreateRequestReply>>;

    /**
     * This endpoint creates an outgoing unstake request for XTZ.  Required role: **RequestCreator**.extractRequestEntity
     * Create an unstake request
     */
    requestServiceCreateOutgoingXTZUnstakeRequest(requestParameters: RequestServiceCreateOutgoingXTZUnstakeRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordCreateRequestReply>;

    /**
     * This endpoint returns the baker of an XTZ address
     * @summary Get XTZ baker
     * @param {string} network 
     * @param {string} address 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestsXTZApiInterface
     */
    xTZBakerServiceGetXTZBakerRaw(requestParameters: XTZBakerServiceGetXTZBakerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordGetXTZBakerReply>>;

    /**
     * This endpoint returns the baker of an XTZ address
     * Get XTZ baker
     */
    xTZBakerServiceGetXTZBaker(requestParameters: XTZBakerServiceGetXTZBakerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordGetXTZBakerReply>;

}

/**
 * 
 */
export class RequestsXTZApi extends runtime.BaseAPI implements RequestsXTZApiInterface {

    /**
     * This endpoint creates an outgoing delegate request for XTZ.  Required role: **RequestCreator**. This API can be made idempotent by generating an ID for the Request beforehand and passing it as the externalRequestId attribute
     * Create a delegate request
     */
    async requestServiceCreateOutgoingXTZDelegateRequestRaw(requestParameters: RequestServiceCreateOutgoingXTZDelegateRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordCreateRequestReply>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling requestServiceCreateOutgoingXTZDelegateRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyTPV1 authentication
        }

        const response = await this.request({
            path: `/api/rest/v1/requests/outgoing/xtz/delegate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TgvalidatordCreateOutgoingXTZDelegateRequestRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TgvalidatordCreateRequestReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint creates an outgoing delegate request for XTZ.  Required role: **RequestCreator**. This API can be made idempotent by generating an ID for the Request beforehand and passing it as the externalRequestId attribute
     * Create a delegate request
     */
    async requestServiceCreateOutgoingXTZDelegateRequest(requestParameters: RequestServiceCreateOutgoingXTZDelegateRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordCreateRequestReply> {
        const response = await this.requestServiceCreateOutgoingXTZDelegateRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint creates an outgoing stake request for XTZ.  Required role: **RequestCreator**. This API can be made idempotent by generating an ID for the Request beforehand and passing it as the externalRequestId attribute
     * Create a stake request
     */
    async requestServiceCreateOutgoingXTZStakeRequestRaw(requestParameters: RequestServiceCreateOutgoingXTZStakeRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordCreateRequestReply>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling requestServiceCreateOutgoingXTZStakeRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyTPV1 authentication
        }

        const response = await this.request({
            path: `/api/rest/v1/requests/outgoing/xtz/stake`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TgvalidatordCreateOutgoingXTZStakeRequestRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TgvalidatordCreateRequestReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint creates an outgoing stake request for XTZ.  Required role: **RequestCreator**. This API can be made idempotent by generating an ID for the Request beforehand and passing it as the externalRequestId attribute
     * Create a stake request
     */
    async requestServiceCreateOutgoingXTZStakeRequest(requestParameters: RequestServiceCreateOutgoingXTZStakeRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordCreateRequestReply> {
        const response = await this.requestServiceCreateOutgoingXTZStakeRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint creates an outgoing undelegate request for XTZ.  Required role: **RequestCreator**.extractRequestEntity
     * Create an undelegate request
     */
    async requestServiceCreateOutgoingXTZUndelegateRequestRaw(requestParameters: RequestServiceCreateOutgoingXTZUndelegateRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordCreateRequestReply>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling requestServiceCreateOutgoingXTZUndelegateRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyTPV1 authentication
        }

        const response = await this.request({
            path: `/api/rest/v1/requests/outgoing/xtz/undelegate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TgvalidatordCreateOutgoingXTZUndelegateRequestRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TgvalidatordCreateRequestReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint creates an outgoing undelegate request for XTZ.  Required role: **RequestCreator**.extractRequestEntity
     * Create an undelegate request
     */
    async requestServiceCreateOutgoingXTZUndelegateRequest(requestParameters: RequestServiceCreateOutgoingXTZUndelegateRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordCreateRequestReply> {
        const response = await this.requestServiceCreateOutgoingXTZUndelegateRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint creates an outgoing unstake request for XTZ.  Required role: **RequestCreator**.extractRequestEntity
     * Create an unstake request
     */
    async requestServiceCreateOutgoingXTZUnstakeRequestRaw(requestParameters: RequestServiceCreateOutgoingXTZUnstakeRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordCreateRequestReply>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling requestServiceCreateOutgoingXTZUnstakeRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyTPV1 authentication
        }

        const response = await this.request({
            path: `/api/rest/v1/requests/outgoing/xtz/unstake`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TgvalidatordCreateOutgoingXTZUnstakeRequestRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TgvalidatordCreateRequestReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint creates an outgoing unstake request for XTZ.  Required role: **RequestCreator**.extractRequestEntity
     * Create an unstake request
     */
    async requestServiceCreateOutgoingXTZUnstakeRequest(requestParameters: RequestServiceCreateOutgoingXTZUnstakeRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordCreateRequestReply> {
        const response = await this.requestServiceCreateOutgoingXTZUnstakeRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint returns the baker of an XTZ address
     * Get XTZ baker
     */
    async xTZBakerServiceGetXTZBakerRaw(requestParameters: XTZBakerServiceGetXTZBakerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordGetXTZBakerReply>> {
        if (requestParameters['network'] == null) {
            throw new runtime.RequiredError(
                'network',
                'Required parameter "network" was null or undefined when calling xTZBakerServiceGetXTZBaker().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling xTZBakerServiceGetXTZBaker().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyTPV1 authentication
        }

        const response = await this.request({
            path: `/api/rest/v1/xtzbakers/{network}/{address}`.replace(`{${"network"}}`, encodeURIComponent(String(requestParameters['network']))).replace(`{${"address"}}`, encodeURIComponent(String(requestParameters['address']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TgvalidatordGetXTZBakerReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint returns the baker of an XTZ address
     * Get XTZ baker
     */
    async xTZBakerServiceGetXTZBaker(requestParameters: XTZBakerServiceGetXTZBakerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordGetXTZBakerReply> {
        const response = await this.xTZBakerServiceGetXTZBakerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
