/* tslint:disable */
/* eslint-disable */
/**
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GooglerpcStatus,
  ScoreServiceRefreshAddressScoreBody,
  ScoreServiceRefreshWLAScoreBody,
  TgvalidatordRefreshScoreReply,
} from '../models/index';
import {
    GooglerpcStatusFromJSON,
    GooglerpcStatusToJSON,
    ScoreServiceRefreshAddressScoreBodyFromJSON,
    ScoreServiceRefreshAddressScoreBodyToJSON,
    ScoreServiceRefreshWLAScoreBodyFromJSON,
    ScoreServiceRefreshWLAScoreBodyToJSON,
    TgvalidatordRefreshScoreReplyFromJSON,
    TgvalidatordRefreshScoreReplyToJSON,
} from '../models/index';

export interface ScoreServiceRefreshAddressScoreRequest {
    addressId: string;
    body: ScoreServiceRefreshAddressScoreBody;
}

export interface ScoreServiceRefreshWLAScoreRequest {
    addressId: string;
    body: ScoreServiceRefreshWLAScoreBody;
}

/**
 * ScoresApi - interface
 * 
 * @export
 * @interface ScoresApiInterface
 */
export interface ScoresApiInterface {
    /**
     * This endpoint refreshes the scores of an address using the specified provider.
     * @summary Refresh address score
     * @param {string} addressId 
     * @param {ScoreServiceRefreshAddressScoreBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScoresApiInterface
     */
    scoreServiceRefreshAddressScoreRaw(requestParameters: ScoreServiceRefreshAddressScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordRefreshScoreReply>>;

    /**
     * This endpoint refreshes the scores of an address using the specified provider.
     * Refresh address score
     */
    scoreServiceRefreshAddressScore(requestParameters: ScoreServiceRefreshAddressScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordRefreshScoreReply>;

    /**
     * This endpoint refreshes the scores of a whitelist address using the specified provider.
     * @summary Refresh WLA score
     * @param {string} addressId 
     * @param {ScoreServiceRefreshWLAScoreBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScoresApiInterface
     */
    scoreServiceRefreshWLAScoreRaw(requestParameters: ScoreServiceRefreshWLAScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordRefreshScoreReply>>;

    /**
     * This endpoint refreshes the scores of a whitelist address using the specified provider.
     * Refresh WLA score
     */
    scoreServiceRefreshWLAScore(requestParameters: ScoreServiceRefreshWLAScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordRefreshScoreReply>;

}

/**
 * 
 */
export class ScoresApi extends runtime.BaseAPI implements ScoresApiInterface {

    /**
     * This endpoint refreshes the scores of an address using the specified provider.
     * Refresh address score
     */
    async scoreServiceRefreshAddressScoreRaw(requestParameters: ScoreServiceRefreshAddressScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordRefreshScoreReply>> {
        if (requestParameters['addressId'] == null) {
            throw new runtime.RequiredError(
                'addressId',
                'Required parameter "addressId" was null or undefined when calling scoreServiceRefreshAddressScore().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling scoreServiceRefreshAddressScore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyTPV1 authentication
        }

        const response = await this.request({
            path: `/api/rest/v1/scores/address/{addressId}/refresh`.replace(`{${"addressId"}}`, encodeURIComponent(String(requestParameters['addressId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScoreServiceRefreshAddressScoreBodyToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TgvalidatordRefreshScoreReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint refreshes the scores of an address using the specified provider.
     * Refresh address score
     */
    async scoreServiceRefreshAddressScore(requestParameters: ScoreServiceRefreshAddressScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordRefreshScoreReply> {
        const response = await this.scoreServiceRefreshAddressScoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint refreshes the scores of a whitelist address using the specified provider.
     * Refresh WLA score
     */
    async scoreServiceRefreshWLAScoreRaw(requestParameters: ScoreServiceRefreshWLAScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TgvalidatordRefreshScoreReply>> {
        if (requestParameters['addressId'] == null) {
            throw new runtime.RequiredError(
                'addressId',
                'Required parameter "addressId" was null or undefined when calling scoreServiceRefreshWLAScore().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling scoreServiceRefreshWLAScore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyTPV1 authentication
        }

        const response = await this.request({
            path: `/api/rest/v1/scores/whitelistedaddress/{addressId}/refresh`.replace(`{${"addressId"}}`, encodeURIComponent(String(requestParameters['addressId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScoreServiceRefreshWLAScoreBodyToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TgvalidatordRefreshScoreReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint refreshes the scores of a whitelist address using the specified provider.
     * Refresh WLA score
     */
    async scoreServiceRefreshWLAScore(requestParameters: ScoreServiceRefreshWLAScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TgvalidatordRefreshScoreReply> {
        const response = await this.scoreServiceRefreshWLAScoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
